(() => {
  const i18n = {
    'zh-CN': {
      'app.title': 'RPG 汉化工作台',
      'app.subtitle': '发布 · 提取 · 校对 · 术语 · 导出',
      'welcome.title': '欢迎使用汉化工作台',
      'welcome.description': '导入 RPG Maker 项目，提取文本、维护术语库，并生成可回写的汉化补丁。',
      'welcome.start': '开始翻译',
      'welcome.demo': '查看示例项目',
      'project.open': '打开游戏项目',
      'project.status': '项目状态',
      'project.unrecognized': '未识别',
      'project.hint': '请选择游戏目录，将自动判断引擎并加载文本。',
      'features.title': '主要能力',
      'features.import': '导入 MV / MZ 项目资源',
      'features.extract': '自动提取对话、选项、名词表文本',
      'features.glossary': '术语库本地保存，可导出术语表',
      'features.export': '导出半成品草稿与汉化补丁目录',
      'glossary.title': '术语库',
      'glossary.panelHint': '点击按钮打开术语库管理器，支持新建、导入、导出和删除操作。',
      'glossary.manage': '管理术语库',
      'workspace.title': '工作区',
      'workspace.exportDraft': '导出草稿',
      'workspace.draftLoad': '载入草稿',
      'workspace.settings': '设置',
      'workspace.clearTexts': '清空当前 JSON 翻译',
      'workspace.clearConfirm': '此操作将清空双语编辑器当前 JSON 文件的所有翻译内容，并将这些条目状态改为未翻译。建议先导出草稿备份。确认继续？',
      'workspace.export': '导出补丁',
      'workspace.noProject': '尚未打开项目',
      'workspace.load': '导出草稿',
      'workspace.ai': '辅助翻译平台',
      'selector.file': 'JSON 文件',
      'selector.search': '搜索',
      'selector.searchPlaceholder': '输入关键词过滤',
      'selector.title': '双语编辑器',
      'selector.hint': '原文译文对照编辑，支持术语与辅助翻译',
      'editor.source': '原文',
      'editor.target': '译文',
      'editor.targetPlaceholder': '输入译文',
      'stats.groups': '文本组数',
      'stats.progress': '总文本数/已翻译数',
      'stats.translated': '已翻译',
      'stats.hits': '术语命中',
      'common.confirm': '确认',
      'common.cancel': '取消',
      'common.edit': '编辑',
      'common.delete': '删除',
      'common.none': '暂无条目',
      'common.aiPending': '正在调用 AI 模型...',
      'common.aiSaved': 'AI 设置已保存。',
      'common.aiSaveFailed': 'AI 设置保存失败。',
      'common.aiTestFail': 'AI 测试失败。',
      'common.aiTestSuccess': 'AI 测试成功。',
      'common.aiTestEmpty': 'AI 测试返回为空。',
      'ai.status': '请选择翻译模式开始翻译。',
      'settings.language': '界面语言',
      'settings.themeMode': '配色模式',
      'settings.themeSystem': '跟随系统',
      'settings.themeDark': '深色',
      'settings.themeLight': '浅色',
      'settings.themePalette': '界面风格颜色',
      'settings.paletteViolet': '梦幻紫',
      'settings.paletteBlue': '极光蓝',
      'settings.paletteEmerald': '翡翠绿',
      'settings.paletteRose': '樱花粉',
      'settings.paletteAmber': '暖琥珀',
      'settings.paletteSlate': '高级灰',
      'settings.backgroundImage': '图片背景',
      'settings.backgroundImagePlaceholder': '输入图片路径或 URL，清空则使用纯色背景',
      'settings.backgroundHint': '支持本地图片路径或网络图片 URL，清空时恢复纯色背景。',
      'settings.pickBackground': '浏览本地图片',
      'settings.previewBackground': '预览当前背景图',
      'settings.applyBackground': '应用但不保存',
      'settings.clearBackground': '清除背景图',
      'settings.resetTheme': '恢复默认外观',
      'settings.previewTitle': '背景预览',
      'settings.previewEmpty': '当前未设置图片背景',
      'settings.tabUI': '界面设置',
      'settings.tabTraditional': '传统翻译',
      'settings.tabLLM': '大模型翻译',
      'settings.titleUI': '界面设置',
      'settings.titleTraditional': '传统翻译设置',
      'settings.titleLLM': '大模型翻译设置',
      'settings.save': '保存设置',
      'settings.close': '关闭',
      'settings.baiduAppId': '百度 App ID',
      'settings.baiduAppIdPlaceholder': '输入你的百度 App ID',
      'settings.baiduSecret': '百度密钥',
      'settings.baiduSecretPlaceholder': '输入你的百度密钥',
      'settings.googleApiKey': 'Google API Key',
      'settings.googleApiKeyPlaceholder': '输入你的 Google API Key',
      'settings.sourceLang': '源语言',
      'settings.sourceLangPlaceholder': 'auto',
      'settings.targetLang': '目标语言',
      'settings.targetLangPlaceholder': 'zh-CN',
      'settings.traditionalHint': '请选择传统翻译服务；百度需要填写平台 APP ID 和密钥，Google 需要 API Key。',
      'settings.llmHint': '适合高质量的翻译、创意一致性和角色感。',
      'glossary.currentProject': '当前项目',
      'glossary.emptyHint': '当前术语库为空，可直接在下方添加。',
      'glossary.termCountHint': '当前术语库含 {count} 条术语。',
      'glossary.confirmDeleteTerm': '确认删除术语 {source}？',
      'glossary.confirmDeleteGlossary': '确认删除术语库 {name}？',
      'glossary.termAdded': '已添加术语条目：{source} → {target}',
      'glossary.termUpdated': '已更新术语条目：{source} → {target}',
      'glossary.termDeleted': '已删除术语条目：{source}',
      'glossary.created': '已新建术语库：{name}',
      'glossary.createdAt': '已新建术语库：{name} 于 {path}',
      'glossary.createCanceled': '已取消新建术语库。',
      'glossary.createFailed': '新建术语库失败',
      'glossary.saveAsApiMissing': '另存接口未注册',
      'glossary.exportApiMissing': '导出接口未注册',
      'glossary.exportCanceled': '已取消导出术语库。',
      'glossary.exported': '已导出术语库：{name}{path}',
      'glossary.imported': '已导入术语库：{name}',
      'glossary.deleted': '已删除术语库：{name}',
      'glossary.loadProjectFirst': '请先打开项目',
      'glossary.importApiMissing': '导入接口未注册',
      'glossary.saveFailed': '术语库保存失败',
      'glossary.listInitFailed': '术语库列表初始化失败',
      'glossary.listRefreshFailed': '术语库列表刷新失败',
      'glossary.exportFailed': '导出失败',
      'glossary.importFailed': '导入失败',
      'glossary.deleteFailed': '删除失败',
      'ai.providerBaidu': '百度翻译',
      'ai.providerGoogle': '谷歌翻译',
      'ai.providerDeepseek': 'DeepSeek',
      'ai.providerGemini': 'Gemini',
      'ai.providerClaude': 'Claude / Anthropic',
      'ai.providerCustom': '自定义接口',
      'ai.apiKeyPlaceholder': '你的 API Key',
      'ai.baseUrlPlaceholder': '接口地址（如 https://api.deepseek.com/chat/completions）',
      'ai.modelPlaceholder': '模型名称（如 deepseek-chat）',
      'ai.promptPlaceholder': '系统提示词（可选）',
      'ai.prompt': '系统提示词',
    },
    en: {
      'app.title': 'RPG Localization Workbench',
      'app.subtitle': 'Release · Extract · Review · Glossary · Export',
      'welcome.title': 'Welcome to the Localization Workbench',
      'welcome.description': 'Import an RPG Maker project, extract text, manage glossaries, and generate patch files.',
      'welcome.start': 'Start Translating',
      'welcome.demo': 'View Demo Project',
      'project.open': 'Open Game Project',
      'project.status': 'Project Status',
      'project.unrecognized': 'Unrecognized',
      'project.hint': 'Select a game directory. The engine will be detected automatically.',
      'features.title': 'Key Features',
      'features.import': 'Import MV / MZ project resources',
      'features.extract': 'Extract dialogues, choices, and name lists',
      'features.glossary': 'Local glossary storage with export support',
      'features.export': 'Export draft and localization patch directory',
      'glossary.title': 'Glossary',
      'glossary.panelHint': 'Open the glossary manager to create, import, export, or delete glossaries.',
      'glossary.manage': 'Manage Glossary',
      'workspace.title': 'Workspace',
      'workspace.exportDraft': 'Export Draft',
      'workspace.draftLoad': 'Load Draft',
      'workspace.settings': 'Settings',
      'workspace.clearTexts': 'Clear Current JSON Translations',
      'workspace.clearConfirm': 'This will clear all translations in the current JSON file and mark entries as untranslated. Export a draft first if needed. Continue?',
      'workspace.export': 'Export Patch',
      'workspace.noProject': 'No project loaded',
      'workspace.load': 'Export Draft',
      'workspace.ai': 'AI Assist',
      'selector.file': 'JSON File',
      'selector.search': 'Search',
      'selector.searchPlaceholder': 'Filter by keyword',
      'selector.title': 'Bilingual Editor',
      'selector.hint': 'Edit source and translation side by side with glossary and assisted translation',
      'editor.source': 'Source',
      'editor.target': 'Translation',
      'editor.targetPlaceholder': 'Enter translation',
      'stats.groups': 'Text Groups',
      'stats.progress': 'Total / Translated',
      'stats.translated': 'Translated',
      'stats.hits': 'Glossary Hits',
      'common.confirm': 'Confirm',
      'common.cancel': 'Cancel',
      'common.edit': 'Edit',
      'common.delete': 'Delete',
      'common.none': 'No items',
      'common.aiPending': 'Calling AI model...',
      'common.aiSaved': 'AI settings saved.',
      'common.aiSaveFailed': 'Failed to save AI settings.',
      'common.aiTestFail': 'AI test failed.',
      'common.aiTestSuccess': 'AI test succeeded.',
      'common.aiTestEmpty': 'AI test returned no result.',
      'ai.status': 'Choose a translation mode to start.',
      'settings.language': 'Interface Language',
      'settings.themeMode': 'Color Mode',
      'settings.themeSystem': 'System',
      'settings.themeDark': 'Dark',
      'settings.themeLight': 'Light',
      'settings.themePalette': 'Color Palette',
      'settings.paletteViolet': 'Violet',
      'settings.paletteBlue': 'Blue',
      'settings.paletteEmerald': 'Emerald',
      'settings.paletteRose': 'Rose',
      'settings.paletteAmber': 'Amber',
      'settings.paletteSlate': 'Slate',
      'settings.backgroundImage': 'Background Image',
      'settings.backgroundImagePlaceholder': 'Enter image path or URL, leave empty for solid color',
      'settings.backgroundHint': 'Supports local paths or remote URLs. Clear to restore solid background.',
      'settings.pickBackground': 'Browse Local Image',
      'settings.previewBackground': 'Preview Background',
      'settings.applyBackground': 'Apply Without Saving',
      'settings.clearBackground': 'Clear Background',
      'settings.resetTheme': 'Restore Defaults',
      'settings.previewTitle': 'Background Preview',
      'settings.previewEmpty': 'No background image set',
      'settings.tabUI': 'Interface',
      'settings.tabTraditional': 'Traditional',
      'settings.tabLLM': 'LLM Translation',
      'settings.titleUI': 'Interface Settings',
      'settings.titleTraditional': 'Traditional Translation Settings',
      'settings.titleLLM': 'LLM Translation Settings',
      'settings.save': 'Save Settings',
      'settings.close': 'Close',
      'settings.baiduAppId': 'Baidu App ID',
      'settings.baiduAppIdPlaceholder': 'Your Baidu App ID',
      'settings.baiduSecret': 'Baidu Secret Key',
      'settings.baiduSecretPlaceholder': 'Your Baidu Secret Key',
      'settings.googleApiKey': 'Google API Key',
      'settings.googleApiKeyPlaceholder': 'Your Google API Key',
      'settings.sourceLang': 'Source Language',
      'settings.sourceLangPlaceholder': 'auto',
      'settings.targetLang': 'Target Language',
      'settings.targetLangPlaceholder': 'zh-CN',
      'settings.traditionalHint': 'Choose a traditional translation service. Baidu requires App ID and Secret; Google requires an API Key.',
      'settings.llmHint': 'Best for high-quality, character-consistent, and stylized translations.',
      'glossary.currentProject': 'Current Project',
      'glossary.emptyHint': 'Glossary is empty. Add terms below.',
      'glossary.termCountHint': 'This glossary contains {count} term(s).',
      'glossary.confirmDeleteTerm': 'Delete term "{source}"?',
      'glossary.confirmDeleteGlossary': 'Delete glossary "{name}"?',
      'glossary.termAdded': 'Term added: {source} → {target}',
      'glossary.termUpdated': 'Term updated: {source} → {target}',
      'glossary.termDeleted': 'Term deleted: {source}',
      'glossary.created': 'Glossary created: {name}',
      'glossary.createdAt': 'Glossary created: {name} at {path}',
      'glossary.createCanceled': 'New glossary cancelled.',
      'glossary.createFailed': 'Failed to create glossary',
      'glossary.saveAsApiMissing': 'Save-as API not registered',
      'glossary.exportApiMissing': 'Export API not registered',
      'glossary.exportCanceled': 'Export cancelled.',
      'glossary.exported': 'Glossary exported: {name}{path}',
      'glossary.imported': 'Glossary imported: {name}',
      'glossary.deleted': 'Glossary deleted: {name}',
      'glossary.loadProjectFirst': 'Please open a project first',
      'glossary.importApiMissing': 'Import API not registered',
      'glossary.saveFailed': 'Failed to save glossary',
      'glossary.listInitFailed': 'Failed to initialize glossary list',
      'glossary.listRefreshFailed': 'Failed to refresh glossary list',
      'glossary.exportFailed': 'Export failed',
      'glossary.importFailed': 'Import failed',
      'glossary.deleteFailed': 'Delete failed',
      'ai.providerBaidu': 'Baidu Translate',
      'ai.providerGoogle': 'Google Translate',
      'ai.providerDeepseek': 'DeepSeek',
      'ai.providerGemini': 'Gemini',
      'ai.providerClaude': 'Claude / Anthropic',
      'ai.providerCustom': 'Custom API',
      'ai.apiKeyPlaceholder': 'Your API Key',
      'ai.baseUrlPlaceholder': 'Endpoint URL (e.g. https://api.deepseek.com/chat/completions)',
      'ai.modelPlaceholder': 'Model name (e.g. deepseek-chat)',
      'ai.promptPlaceholder': 'System prompt (optional)',
      'ai.prompt': 'System Prompt',
    },
    ja: {
      'app.title': 'RPG ローカライズワークベンチ',
      'app.subtitle': 'リリース · 抽出 · 校正 · 用語集 · エクスポート',
      'welcome.title': 'ローカライズワークベンチへようこそ',
      'welcome.description': 'RPG Maker プロジェクトをインポートし、テキストを抽出・用語を管理・パッチを生成します。',
      'welcome.start': '翻訳を開始',
      'welcome.demo': 'デモを見る',
      'project.open': 'ゲームプロジェクトを開く',
      'project.status': 'プロジェクト状態',
      'project.unrecognized': '未認識',
      'project.hint': 'ゲームディレクトリを選択してください。エンジンを自動検出します。',
      'features.title': '主な機能',
      'features.import': 'MV / MZ プロジェクトリソースのインポート',
      'features.extract': '会話・選択肢・名詞リストの自動抽出',
      'features.glossary': '用語集のローカル保存とエクスポート',
      'features.export': '草稿とローカライズパッチの出力',
      'glossary.title': '用語集',
      'glossary.panelHint': '用語集マネージャーを開いて作成・インポート・エクスポート・削除が可能です。',
      'glossary.manage': '用語集を管理',
      'workspace.title': 'ワークスペース',
      'workspace.exportDraft': '草稿を出力',
      'workspace.draftLoad': '草稿を読み込む',
      'workspace.settings': '設定',
      'workspace.clearTexts': '現在の JSON 翻訳をクリア',
      'workspace.clearConfirm': 'バイリンガルエディターで表示中の JSON ファイルの全翻訳をクリアし、エントリを未翻訳にします。必要なら先に草稿をエクスポートしてください。続行しますか？',
      'workspace.export': 'パッチを出力',
      'workspace.noProject': 'プロジェクト未読み込み',
      'workspace.load': '草稿を出力',
      'workspace.ai': 'AI 翻訳補助',
      'selector.file': 'JSON ファイル',
      'selector.search': '検索',
      'selector.searchPlaceholder': 'キーワードで絞り込む',
      'selector.title': 'バイリンガルエディター',
      'selector.hint': '原文と翻訳を並べて編集。用語集と翻訳補助に対応',
      'editor.source': '原文',
      'editor.target': '翻訳',
      'editor.targetPlaceholder': '翻訳を入力',
      'stats.groups': 'テキストグループ',
      'stats.progress': '合計 / 翻訳済み',
      'stats.translated': '翻訳済み',
      'stats.hits': '用語ヒット',
      'common.confirm': '確認',
      'common.cancel': 'キャンセル',
      'common.edit': '編集',
      'common.delete': '削除',
      'common.none': 'アイテムなし',
      'common.aiPending': 'AI モデルを呼び出し中...',
      'common.aiSaved': 'AI 設定を保存しました。',
      'common.aiSaveFailed': 'AI 設定の保存に失敗しました。',
      'common.aiTestFail': 'AI テストに失敗しました。',
      'common.aiTestSuccess': 'AI テストに成功しました。',
      'common.aiTestEmpty': 'AI テストの結果が空です。',
      'ai.status': '翻訳モードを選択して開始してください。',
      'settings.language': 'インターフェース言語',
      'settings.themeMode': '配色モード',
      'settings.themeSystem': 'システムに従う',
      'settings.themeDark': 'ダーク',
      'settings.themeLight': 'ライト',
      'settings.themePalette': 'カラーパレット',
      'settings.paletteViolet': 'バイオレット',
      'settings.paletteBlue': 'ブルー',
      'settings.paletteEmerald': 'エメラルド',
      'settings.paletteRose': 'ローズ',
      'settings.paletteAmber': 'アンバー',
      'settings.paletteSlate': 'スレート',
      'settings.backgroundImage': '背景画像',
      'settings.backgroundImagePlaceholder': '画像パスまたは URL を入力（空で単色背景）',
      'settings.backgroundHint': 'ローカルパスまたはリモート URL をサポート。空にすると単色に戻ります。',
      'settings.pickBackground': 'ローカル画像を参照',
      'settings.previewBackground': '背景をプレビュー',
      'settings.applyBackground': '適用（保存なし）',
      'settings.clearBackground': '背景をクリア',
      'settings.resetTheme': 'デフォルトに戻す',
      'settings.previewTitle': '背景プレビュー',
      'settings.previewEmpty': '背景画像が設定されていません',
      'settings.tabUI': 'インターフェース',
      'settings.tabTraditional': '従来型翻訳',
      'settings.tabLLM': 'LLM 翻訳',
      'settings.titleUI': 'インターフェース設定',
      'settings.titleTraditional': '従来型翻訳設定',
      'settings.titleLLM': 'LLM 翻訳設定',
      'settings.save': '設定を保存',
      'settings.close': '閉じる',
      'settings.baiduAppId': 'Baidu App ID',
      'settings.baiduAppIdPlaceholder': 'Baidu App ID を入力',
      'settings.baiduSecret': 'Baidu シークレットキー',
      'settings.baiduSecretPlaceholder': 'Baidu シークレットキーを入力',
      'settings.googleApiKey': 'Google API Key',
      'settings.googleApiKeyPlaceholder': 'Google API Key を入力',
      'settings.sourceLang': 'ソース言語',
      'settings.sourceLangPlaceholder': 'auto',
      'settings.targetLang': 'ターゲット言語',
      'settings.targetLangPlaceholder': 'zh-CN',
      'settings.traditionalHint': '従来型翻訳サービスを選択。Baidu は App ID とシークレット、Google は API Key が必要です。',
      'settings.llmHint': '高品質・キャラクター一貫性・スタイル翻訳に最適です。',
      'glossary.currentProject': '現在のプロジェクト',
      'glossary.emptyHint': '用語集が空です。下部から追加できます。',
      'glossary.termCountHint': 'この用語集には {count} 件の用語が含まれています。',
      'glossary.confirmDeleteTerm': '用語 "{source}" を削除しますか？',
      'glossary.confirmDeleteGlossary': '用語集 "{name}" を削除しますか？',
      'glossary.termAdded': '用語を追加しました：{source} → {target}',
      'glossary.termUpdated': '用語を更新しました：{source} → {target}',
      'glossary.termDeleted': '用語を削除しました：{source}',
      'glossary.created': '用語集を作成しました：{name}',
      'glossary.createdAt': '用語集を作成しました：{name}（{path}）',
      'glossary.createCanceled': '用語集の作成をキャンセルしました。',
      'glossary.createFailed': '用語集の作成に失敗しました',
      'glossary.saveAsApiMissing': '別名保存 API が未登録です',
      'glossary.exportApiMissing': 'エクスポート API が未登録です',
      'glossary.exportCanceled': 'エクスポートをキャンセルしました。',
      'glossary.exported': '用語集をエクスポートしました：{name}{path}',
      'glossary.imported': '用語集をインポートしました：{name}',
      'glossary.deleted': '用語集を削除しました：{name}',
      'glossary.loadProjectFirst': 'プロジェクトを先に開いてください',
      'glossary.importApiMissing': 'インポート API が未登録です',
      'glossary.saveFailed': '用語集の保存に失敗しました',
      'glossary.listInitFailed': '用語集リストの初期化に失敗しました',
      'glossary.listRefreshFailed': '用語集リストの更新に失敗しました',
      'glossary.exportFailed': 'エクスポートに失敗しました',
      'glossary.importFailed': 'インポートに失敗しました',
      'glossary.deleteFailed': '削除に失敗しました',
      'ai.providerBaidu': '百度翻訳',
      'ai.providerGoogle': 'Google 翻訳',
      'ai.providerDeepseek': 'DeepSeek',
      'ai.providerGemini': 'Gemini',
      'ai.providerClaude': 'Claude / Anthropic',
      'ai.providerCustom': 'カスタム API',
      'ai.apiKeyPlaceholder': 'API キーを入力',
      'ai.baseUrlPlaceholder': 'エンドポイント URL（例：https://api.deepseek.com/chat/completions）',
      'ai.modelPlaceholder': 'モデル名（例：deepseek-chat）',
      'ai.promptPlaceholder': 'システムプロンプト（任意）',
      'ai.prompt': 'システムプロンプト',
    },
  };

  function t(key) {
    const lang = localStorage.getItem('rpg-workbench-language') || 'zh-CN';
    const dict = i18n[lang] || i18n['zh-CN'];
    return dict[key] || i18n['zh-CN'][key] || key;
  }

  window.RpgI18n = i18n;
  window.RpgView = window.RpgView || {};
  window.RpgView.t = t;

  window.setVersionLabel = () => {
    const badge = document.getElementById('appVersionBadge');
    const copyright = document.getElementById('appCopyright');
    if (badge) badge.textContent = 'v 1.2.0';
    if (copyright) copyright.textContent = '© 2026 RPG 汉化工作台，保留所有权利。';
  };

  window.showProjectStatus = window.showProjectStatus || (() => {});
  window.showAiStatus = window.showAiStatus || (() => {});
  window.showTraditionalStatus = window.showTraditionalStatus || (() => {});
  window.showToast = window.showToast || (() => {});
  window.setCallTraceStatus = window.setCallTraceStatus || (() => {});
  window.traceCall = window.traceCall || (() => {});
})();