(() => {
  const i18n = {
    'zh-CN': {
      'app.title': 'RPG 汉化工作台',
      'app.subtitle': '发布 · 提取 · 校对 · 术语 · 导出',
      'welcome.title': '欢迎使用汉化工作台',
      'welcome.description': '导入 RPG Maker 项目，提取文本、维护术语库，并生成可回写的汉化补丁。',
      'welcome.start': '开始翻译',
      'welcome.demo': '查看示例项目',
      'project.open': '打开游戏项目',
      'project.status': '项目状态',
      'project.unrecognized': '未识别',
      'project.hint': '请选择游戏目录，将自动判断引擎并加载文本。',
      'project.recognized': '已识别',
      'project.recognizedHint': '已识别到项目结构，可继续导入与翻译。',
      'project.dataRootsFound': '已扫描到 {count} 个文本目录',
      'project.dataRootsEmpty': '未扫描到文本目录',
      'project.statusLoaded': '项目已加载',
      'project.statusDraft': '草稿已加载',
      'project.statusLoading': '正在加载项目…',
      'project.ready': '项目已就绪：{path}',
      'trace.projectStatus': '项目状态打点',
      'trace.openProject': '打开项目',
      'trace.loadDraftBtn': '载入草稿按钮',
      'trace.prepareRead': '准备读取：{path}',
      'trace.callSystemDirPicker': '开始调用系统目录选择器',
      'trace.userCancel': '用户取消选择',
      'trace.pickResult': '选择结果 rootDir={rootDir}, engine={engine}',
      'trace.mainProcessReturn': '主进程返回 entries={entries}, warnings={warnings}',
      'trace.startPickDraftFile': '开始选择草稿文件',
      'trace.draftOpened': '已打开 {path}',
      'common.processing': '正在处理',
      'common.unknownError': '未知错误',
      'common.operationFailed': '操作失败',
      'draft.loadFailed': '草稿加载失败',
      'draft.loaded': '已载入草稿：{path}',
      'project.scanDataRootsDone': '已发现文本目录：{count} 个',
      'project.scanDataRootsEmpty': '未发现可扫描的数据目录，请检查项目结构。',
      'project.scanDataRootsFailed': '扫描文本位置失败：{message}',
      'project.scanDataRootsMissing': '请先打开项目再扫描文本位置。',
      'project.scanningDataRoots': '正在扫描文本目录…',
      'features.title': '主要能力',
      'features.import': '导入 MV / MZ 项目资源',
      'features.extract': '自动提取对话、选项、名词表文本',
      'features.glossary': '术语库本地保存，可导出术语表',
      'features.export': '导出半成品草稿与汉化补丁目录',
      'glossary.title': '术语库',
      'glossary.panelHint': '点击按钮打开术语库管理器，支持新建、导入、导出和删除操作。',
      'glossary.manage': '管理术语库',
      'workspace.title': '工作区',
      'workspace.exportDraft': '导出草稿',
      'workspace.draftLoad': '载入草稿',
      'workspace.settings': '设置',
      'workspace.clearTexts': '清空当前 JSON 翻译',
      'workspace.clearConfirm': '此操作将清空双语编辑器当前 JSON 文件的所有翻译内容，并将这些条目状态改为未翻译。建议先导出草稿备份。确认继续？',
      'workspace.export': '导出补丁',
      'workspace.noProject': '尚未打开项目',
      'workspace.load': '导出草稿',
      'workspace.ai': '辅助翻译平台',
      'selector.file': 'JSON 文件',
      'selector.search': '搜索',
      'selector.searchPlaceholder': '输入关键词过滤',
      'selector.searchScope': '搜索范围',
      'selector.searchScopeCurrent': '当前 JSON',
      'selector.searchScopeAll': '全部 JSON',
      'selector.title': '双语编辑器',
      'selector.hint': '原文译文对照编辑，支持术语与辅助翻译',
      'editor.source': '原文',
      'editor.target': '译文',
      'editor.targetPlaceholder': '输入译文',
      'stats.groups': '文本组数',
      'stats.files': '文件数',
      'stats.progress': '总文本数/已翻译数',
      'stats.translated': '已翻译',
      'stats.hits': '术语命中',
      'progress.global': '项目进度',
      'progress.currentFile': '当前文件进度',
      'progress.file': '文件进度',
      'progress.translated': '已翻译',
      'progress.pending': '未翻译',
      'progress.reviewed': '已校对',
      'progress.warning': '预警',
      'progress.lastPosition': '上次翻译位置',
      'progress.continueLast': '继续上次翻译',
      'progress.gotoLast': '跳到上次位置',
      'progress.nextPending': '下一个未翻译',
      'progress.previousPending': '上一个未翻译',
      'progress.filterPending': '只看未翻译',
      'progress.filterWarnings': '只看有预警',
      'progress.filterContextual': '只看上下文文本',
      'progress.filterAtomic': '只看独立词条',
      'progress.noLastPosition': '暂无上次翻译位置',
      'progress.noPending': '暂无未翻译条目',
      'progress.summary': '{translated}/{total} · {percent}%',
      'progress.toggleStatus': '点击切换翻译状态',
      'context.viewMode': '翻译模式',
      'context.singleMode': '单条模式',
      'context.groupMode': '上下文组模式',
      'context.scrollSync': '同步滚动位置',
      'context.scrollSyncTitle': '勾选后单条翻译模式与上下文组翻译模式的滚动位置同步；勾选瞬间会把非活动模式的位置对齐到当前模式',
      'context.noGroups': '当前文件暂无上下文组',
      'context.groupTargetPlaceholder': '输入该上下文组的整体译文',
      'context.groupShort': '上下文组',
      'context.groupSummary': '上下文组 · {count} 条 · {keys}',
      'context.groupEmpty': '勾选下方条目组成上下文组，可整体翻译并按 \\N 标记自动拆回各行。',
      'context.sourcePlaceholder': '可手动编辑此区域以调整断句，使用 \\N 标记分段（与下方译文段数一一对应）',
      'context.targetPlaceholder': '输入该上下文组的整体译文，使用 \\N 快速分行',
      'context.previewLabel': '译文预览（点击行间分隔条插入 / 移除 \\N 分行标记；可直接在上方输入 \\N）',
      'context.previewInsert': '点击插入 \\N 分行标记',
      'context.previewRemove': '点击移除 \\N 分行标记',
      'context.previewEmptyLine': '（空行）',
      'context.splitHint': '点击 "AI 翻译整组" 时：对 DeepSeek / OpenAI / Claude 等 LLM 自动启用 JSON 结构化协议（输入 / 输出都按编号键值对一一对应，response_format 强制 JSON 输出）；对百度 / 谷歌等传统翻译则走 \\N 文本协议。RPG Maker 控制码（\\N[1] / \\V[3] / \\C[10] 等）会被替换为 {{RPG_CODE_n}} 占位符发送给 AI，返回后原样还原。段数不匹配会自动诊断式重试至多 2 次。',
      'context.aiTranslateGroup': 'AI 翻译整组',
      'context.aiTranslateGroupTitle': '把原文 textarea 编辑后的整段发送给 AI；程序自动包装分句协议、保护控制码、按段数校验并在必要时自动重试',
      'context.applyToSelected': '应用到所选',
      'context.clearSelection': '清空选择',
      'context.listFilterPlaceholder': '在备选条目中搜索原文 / key…',
      'context.backToTop': '回到顶部',
      'context.backToTopTitle': '把备选条目列表的滚动条滚到最顶部',
      'context.sourceEmpty': '原文框为空，无法翻译',
      'context.aiCalling': '调用 AI（{provider}）…',
      'context.aiRetrying': '段数不符（{actual}/{expected}），正在以诊断性重试 {attempt}/{max}…',
      'context.aiSegmentCountWarn': '提示：原文 textarea 中的分段数 {input} ≠ 所选条目数 {expected}，将按 {expected} 段约束输出',
      'context.aiSuccess': '已使用 {provider} 完成编组翻译，精准回填 {count}/{expected} 段',
      'context.aiSuccessWithRetry': '已使用 {provider} 完成编组翻译，精准回填 {count}/{expected} 段（重试 {retried} 次后达成对齐）',
      'context.aiFailRetained': '编组翻译失败：{reason}（共调用 {attempts} 次，未达成段数对齐；已把尽力结果展示在译文框，请人工调整后点 "应用到所选"）',
      'context.aiFailEmpty': '编组翻译失败：{reason}',
      'context.aiTraceSuccess': '对齐成功 {count}/{expected}；attempts={attempts}；reason={reason}',
      'context.aiTracePending': '使用 {provider} 翻译编组：{count} 条（含控制码保护与重试）',
      'context.aiSegmentMismatch': '译文段数不匹配（实际 {actual} 段，要求 {expected} 段）',
      'context.aiRetryExhausted': '{reason}；已诊断式重试 {max} 次仍未达成对齐',
      'context.aiTraceLabel': '编组翻译',
      'context.aiTradBatchProgress': '逐条翻译（{current}/{total}）…',
      'context.aiTradBatchFailed': '第 {index} 段翻译失败：{reason}',
      'progress.jumpFail': '目标位置不存在或已被移除',
      'progress.gotoLastDone': '{action} → {file} #{index}',
      'textClass.contextual': '上下文文本',
      'textClass.atomic': '独立词条',
      'textClass.mixed': '混合文本',
      'textClass.unknown': '未知类型',
      'textType.dialogue-line': '对话行',
      'textType.dialogue-block': '对话组',
      'textType.long-description': '长文本',
      'textType.choice-option': '选项',
      'textType.actor-name': '角色名',
      'textType.actor-description': '角色描述',
      'textType.enemy-name': '敌人名',
      'textType.enemy-description': '敌人描述',
      'textType.item-name': '物品名',
      'textType.item-description': '物品描述',
      'textType.items-description': '物品描述',
      'textType.weapon-name': '武器名',
      'textType.weapon-description': '武器描述',
      'textType.weapons-description': '武器描述',
      'textType.armor-name': '防具名',
      'textType.armor-description': '防具描述',
      'textType.armors-description': '防具描述',
      'textType.skill-name': '技能名',
      'textType.skill-description': '技能描述',
      'textType.skills-description': '技能描述',
      'textType.state-name': '状态名',
      'textType.state-description': '状态描述',
      'textType.states-description': '状态描述',
      'textType.class-name': '职业名',
      'textType.class-description': '职业描述',
      'textType.classes-description': '职业描述',
      'textType.map-name': '地图名',
      'textType.system-command': '系统命令',
      'textType.system-message': '系统消息',
      'textType.system-title': '系统标题',
      'textType.currency-unit': '货币单位',
      'textType.event-message': '事件消息',
      'textType.speaker': '说话者',
      'textType.plugin-text': '插件文本',
      'textType.generic-text': '通用文本',
      'glossary.hitCount': '术语命中 {count} 条',
      'glossary.insertMode': '插入方式',
      'glossary.insertCursor': '插入到光标处',
      'glossary.insertReplace': '替换选中文本',
      'glossary.insertAppend': '追加到末尾',
      'glossary.insertAll': '一键插入全部',
      'glossary.insertOne': '插入：{source} → {target}',
      'glossary.insertAllDone': '已插入全部术语，共 {count} 条。',
      'glossary.insertOneDone': '已将术语插入译文：{source}',
      'entry.aiTranslate': 'AI翻译',
      'entry.aiTranslateTitle': '使用当前选择的辅助翻译平台翻译本条文本',
      'entry.preview': '预览',
      'entry.previewTitle': '在游戏中预览当前翻译',
      'entry.previewEmpty': '译文为空，无法预览',
      'entry.previewPending': '正在启动游戏预览…',
      'entry.previewApiMissing': '预览接口不可用',
      'entry.previewStarted': '预览已启动 (PID: {pid})',
      'entry.repreviewStarted': '预览点位已更新 (PID: {pid})',
      'entry.previewFailed': '预览启动失败',
      'entry.previewGroupTitle': '以首句为入口预览整组译文',
      'entry.previewNoSibling': '当前事件没有更多相邻句子',
      'preview.embeddedTitle': '游戏预览',
      'preview.embeddedHint': '游戏窗口将嵌入下方区域，关闭游戏或点击右侧按钮即可恢复备份',
      'preview.buttonPrev': '上一句',
      'preview.buttonNext': '下一句',
      'preview.buttonTitle': '返回标题',
      'preview.close': '关闭预览',
      'preview.tvPlaceholder': '点击译文行的「预览」按钮，游戏画面将显示在这里',
      'preview.tvPower': '电源',
      'common.confirm': '确认',
      'common.cancel': '取消',
      'common.edit': '编辑',
      'common.delete': '删除',
      'common.none': '暂无条目',
      'common.aiPending': '正在调用 AI 模型...',
      'common.aiSaved': 'AI 设置已保存。',
      'common.aiSaveFailed': 'AI 设置保存失败。',
      'common.aiTestFail': 'AI 测试失败。',
      'common.aiTestSuccess': 'AI 测试成功。',
      'common.aiTestEmpty': 'AI 测试返回为空。',
      'ai.status': '请选择翻译模式开始翻译。',
      'settings.language': '界面语言',
      'settings.themeMode': '配色模式',
      'settings.themeSystem': '跟随系统',
      'settings.themeDark': '深色',
      'settings.themeLight': '浅色',
      'settings.themePalette': '界面风格颜色',
      'settings.paletteViolet': '梦幻紫',
      'settings.paletteBlue': '极光蓝',
      'settings.paletteEmerald': '翡翠绿',
      'settings.paletteRose': '樱花粉',
      'settings.paletteAmber': '暖琥珀',
      'settings.paletteSlate': '高级灰',
      'settings.backgroundImage': '图片背景',
      'settings.backgroundImagePlaceholder': '输入图片路径或 URL，清空则使用纯色背景',
      'settings.backgroundHint': '支持本地图片路径或网络图片 URL，清空时恢复纯色背景。',
      'settings.closeBehavior': '关闭按钮行为',
      'settings.closeBehaviorTray': '最小化到右下角托盘',
      'settings.closeBehaviorExit': '直接退出程序',
      'settings.closeBehaviorHint': '选择“最小化到托盘”后，点击右上角 X 不会真正退出，而是隐藏到系统托盘；再次打开托盘即可恢复窗口。选择“直接退出程序”则点击 X 会正常关闭应用。',
      'settings.previewGroupTitle': '游戏内预览',
      'settings.enableGamePreview': '启用游戏内快速预览（仅在 RPG Maker MV/MZ 项目中显示）',
      'settings.enableGamePreviewHint': '关闭后，单条模式与上下文组模式中的「预览」按钮将不再显示。',
      'settings.previewWindowMode': '预览窗口模式',
      'settings.previewWindowModePopup': '弹出式独立窗口（Game.exe）',
      'settings.previewWindowModeEmbedded': '嵌入主窗口底部',
      'settings.showPreviewNotification': '启动预览时在游戏中显示“文本内容预览模式”提示',
      'settings.previewNotificationPosition': '提示文字位置',
      'settings.previewNotificationPositionTopLeft': '顶部左侧',
      'settings.previewNotificationPositionTopCenter': '顶部居中',
      'settings.previewNotificationPositionTopRight': '顶部右侧',
      'settings.previewNotificationPositionBottomLeft': '底部左侧',
      'settings.previewNotificationPositionBottomCenter': '底部居中',
      'settings.previewNotificationPositionBottomRight': '底部右侧',
      'settings.pickBackground': '浏览本地图片',
      'settings.previewBackground': '预览当前背景图',
      'settings.applyBackground': '应用但不保存',
      'settings.clearBackground': '清除背景图',
      'settings.resetTheme': '恢复默认外观',
      'settings.previewTitle': '背景预览',
      'settings.previewEmpty': '当前未设置图片背景',
      'settings.tabUI': '界面设置',
      'settings.tabTraditional': '传统翻译',
      'settings.tabLLM': '大模型翻译',
      'settings.titleUI': '界面设置',
      'settings.titleTraditional': '传统翻译设置',
      'settings.titleLLM': '大模型翻译设置',
      'settings.save': '保存设置',
      'settings.close': '关闭',
      'settings.baiduAppId': '百度 App ID',
      'settings.baiduAppIdPlaceholder': '输入你的百度 App ID',
      'settings.baiduSecret': '百度密钥',
      'settings.baiduSecretPlaceholder': '输入你的百度密钥',
      'settings.googleApiKey': 'Google API Key',
      'settings.googleApiKeyPlaceholder': '输入你的 Google API Key',
      'settings.sourceLang': '源语言',
      'settings.sourceLangPlaceholder': 'auto',
      'settings.targetLang': '目标语言',
      'settings.targetLangPlaceholder': 'zh-CN',
      'settings.traditionalHint': '请选择传统翻译服务；百度需要填写平台 APP ID 和密钥，Google 需要 API Key。',
      'settings.llmHint': '适合高质量的翻译、创意一致性和角色感。',
      'glossary.currentProject': '当前项目',
      'glossary.emptyHint': '当前术语库为空，可直接在下方添加。',
      'glossary.termCountHint': '当前术语库含 {count} 条术语。',
      'glossary.confirmDeleteTerm': '确认删除术语 {source}？',
      'glossary.confirmDeleteGlossary': '确认删除术语库 {name}？',
      'glossary.termAdded': '已添加术语条目：{source} → {target}',
      'glossary.termUpdated': '已更新术语条目：{source} → {target}',
      'glossary.termDeleted': '已删除术语条目：{source}',
      'glossary.created': '已新建术语库：{name}',
      'glossary.createdAt': '已新建术语库：{name} 于 {path}',
      'glossary.createCanceled': '已取消新建术语库。',
      'glossary.createFailed': '新建术语库失败',
      'glossary.saveAsApiMissing': '另存接口未注册',
      'glossary.exportApiMissing': '导出接口未注册',
      'glossary.exportCanceled': '已取消导出术语库。',
      'glossary.exported': '已导出术语库：{name}{path}',
      'glossary.imported': '已导入术语库：{name}',
      'glossary.deleted': '已删除术语库：{name}',
      'glossary.saving': '正在保存术语库…',
      'glossary.creating': '正在新建术语库…',
      'glossary.exporting': '正在导出术语库…',
      'glossary.importing': '正在导入术语库…',
      'glossary.renaming': '正在重命名术语库：{from} → {to}',
      'glossary.loadProjectFirst': '请先打开项目',
      'glossary.importApiMissing': '导入接口未注册',
      'glossary.saveFailed': '术语库保存失败',
      'glossary.listInitFailed': '术语库列表初始化失败',
      'glossary.listRefreshFailed': '术语库列表刷新失败',
      'glossary.exportFailed': '导出失败',
      'glossary.importFailed': '导入失败',
      'glossary.deleteFailed': '删除失败',
      'validation.tooManyLines': '{actual}/{max} 行',
      'validation.lineTooLong': '第{line}行{actual}/{max}字',
      'validation.missingControlCodes': '缺控制码 {codes}',
      'ai.defaultSystemPrompt': '你是一个专业的 RPG Maker 游戏汉化助手，请将原文自然准确地翻译成简体中文。',
      'ai.providerBaidu': '百度翻译',
      'ai.providerGoogle': '谷歌翻译',
      'ai.providerDeepseek': 'DeepSeek',
      'ai.providerKimi': 'Kimi（月之暗面）',
      'ai.providerGemini': 'Gemini',
      'ai.providerClaude': 'Claude / Anthropic',
      'ai.providerCustom': '自定义 OpenAI 兼容接口',
      'ai.apiKeyPlaceholder': '你的 API Key',
      'ai.baseUrlPlaceholder': '接口地址（如 https://api.deepseek.com/chat/completions）',
      'ai.modelPlaceholder': '模型名称（如 deepseek-chat）',
      'ai.promptPlaceholder': '系统提示词（可选）',
      'ai.prompt': '系统提示词',
      'ai.kimiTutorialTitle': 'Kimi（月之暗面）配置教程',
      'ai.kimiStep1': '1. 选择端点：Kimi 有两条独立端点，密钥不通用：国际版 platform.kimi.ai 对应 base_url https://api.moonshot.ai/v1；国内版 platform.moonshot.cn 对应 base_url https://api.moonshot.cn/v1。务必把 Key 与其来源端点配对，跨端点使用会得到 HTTP 401。',
      'ai.kimiStep2': '2. 在对应控制台的「API Keys」页面点击「新建 API Key」，复制 sk- 开头的密钥，粘贴到上方「API Key」输入框（右侧眼睛可切换显示）。',
      'ai.kimiStep3': '3. 接口地址按你的账号来源二选一：https://api.moonshot.ai/v1（国际）或 https://api.moonshot.cn/v1（国内）。必须带 /v1，程序会自动拼 /chat/completions。',
      'ai.kimiStep4': '4. 模型下拉里推荐日常翻译选 moonshot-v1-8k（8K 上下文最便宜）；长文本可选 moonshot-v1-32k / moonshot-v1-128k；追求最强质量可选 kimi-k2.6。',
      'ai.kimiStep5': '5. 已停用：kimi-latest（2026-01-28 下线）与 kimi-k2-*-preview 系列（2026-05-25 下线），请不要使用。',
      'ai.kimiStep6': '6. 保存后点击「测试大模型翻译」验证；若得到 401 大概率是端点与 Key 来源不匹配，请回控制台核对来源与余额后重试。',
      'ai.toggleKeyShow': '显示密钥',
      'ai.toggleKeyHide': '隐藏密钥',
      'ai.deepseekV4Flash': 'deepseek-v4-flash（官方推荐，非思考）',
      'ai.deepseekV4Pro': 'deepseek-v4-pro（官方推荐，思考）',
      'ai.deepseekChat': 'deepseek-chat（旧兼容名，将弃用）',
      'ai.deepseekReasoner': 'deepseek-reasoner（旧兼容名，将弃用）',
      'app.version': '· 1.2.0',
      'language.zhCN': '简体中文',
      'language.en': 'English',
      'language.ja': '日本語',
      'workspace.applyWritebackTitle': '把当前译文按原结构写回新 JSON（不覆盖原文件，输出到 localization_patch/data/）',
      'workspace.stopPreview': '停止游戏预览',
      'workspace.stopPreviewTitle': '强制停止游戏预览并恢复被修改的原始 JSON 备份',
      'workspace.stoppingPreview': '正在停止游戏预览并恢复备份…',
      'workspace.returnToTitle': '退回标题画面',
      'workspace.returnToTitleTitle': '不关闭游戏，直接退回标题画面（F12）',
      'workspace.returningToTitle': '正在退回标题画面…',
      'workspace.returnedToTitle': '已退回标题画面',
      'workspace.returnToTitleFailed': '退回标题失败',
      'workspace.previewStopped': '已停止游戏预览',
      'workspace.previewStoppedRestored': '已恢复 {files} 个预览备份文件',
      'workspace.previewStopFailed': '停止预览失败',
      'workspace.previewProcessExited': '游戏预览进程已结束，备份已恢复',
      'project.previewBackupsRestored': '检测到上次崩溃残留的预览备份，已自动恢复 {files} 个文件',
      'trace.project': '项目',
      'trace.aiTranslate': 'AI翻译',
      'trace.traditionalTranslate': '传统翻译',
      'trace.notice': '提示',
      'trace.status': '状态',
      'trace.assistPlatform': '辅助翻译平台',
      'trace.providerSwitched': '已切换至 {provider}',
      'trace.uiSettings': '界面设置',
      'trace.uiSettingsSaved': '界面设置已保存。',
      'trace.backgroundImage': '背景图片',
      'trace.selectFailed': '选择失败',
      'trace.defaultThemeRestored': '已恢复默认外观',
      'trace.waiting': '等待操作…',
      'trace.initFailed': '初始化失败',
      'trace.unknownError': '未知错误',
      'trace.aiSettings': '大模型翻译设置',
      'trace.aiTest': '大模型翻译测试',
      'trace.traditionalSettings': '传统翻译设置',
      'trace.traditionalTest': '传统翻译测试',
      'app.copyright': '© 2026 RPG 汉化工作台，保留所有权利。',
    
      'action.openProjectFolder': '打开项目目录',
      'action.loadProjectTexts': '载入项目文本',
      'action.saveTranslatorSettings': '保存翻译设置',
      'action.testTranslatorSettings': '测试翻译设置',
      'action.aiTranslate': 'AI 翻译',
      'action.previewInGame': '游戏内预览',
      'action.repreviewInGame': '更新预览点位',
      'action.returnToTitle': '退回标题画面',
      'action.stopPreview': '停止游戏预览',
      'action.saveProjectLastPosition': '保存翻译位置',
      'action.loadProjectProgressState': '读取项目进度',
      'action.getUiSettings': '读取界面设置',
      'action.saveUiSettings': '保存界面设置',
      'trace.actionStart': '动作开始',
      'trace.actionSuccess': '动作完成',
      'trace.actionFailed': '动作失败',
      'error.projectRequired': '{action}前请先打开并载入项目',
      'error.saveDraftApiMissing': '草稿导出接口未注入',
      'error.exportDraftFailed': '导出草稿失败',
      'error.exportPatchApiMissing': '补丁导出接口未注入',
      'error.exportPatchFailed': '导出补丁失败',
      'error.writebackApiMissing': '写回接口未注入',
      'error.writebackFailed': '写回失败',
      'action.exportDraft': '导出草稿',
      'action.exportPatch': '导出补丁',
      'action.writebackJson': '写回 JSON',
      'export.draftPending': '正在导出草稿…',
      'export.draftSuccess': '草稿导出完成',
      'export.draftError': '草稿导出失败',
      'export.patchPending': '正在导出补丁…',
      'export.patchSuccess': '补丁导出完成',
      'export.patchError': '补丁导出失败',
      'trace.writebackClicked': '点击写回游戏 JSON',
      'action.openPatchDir': '打开补丁目录',
      'error.noPatchDir': '没有可打开的补丁目录',
      'error.openDirApiMissing': '打开目录接口未注入',
      'action.openingPatchDir': '正在打开补丁目录…',
      'action.patchDirOpened': '补丁目录已打开',
      'action.openPatchDirFailed': '打开补丁目录失败',
      'writeback.summary': '已写回 {count} 个 JSON 文件（含 {errors} 条错误）',
    },
    en: {
      'app.title': 'RPG Localization Workbench',
      'app.subtitle': 'Release · Extract · Review · Glossary · Export',
      'welcome.title': 'Welcome to the Localization Workbench',
      'welcome.description': 'Import an RPG Maker project, extract text, manage glossaries, and generate patch files.',
      'welcome.start': 'Start Translating',
      'welcome.demo': 'View Demo Project',
      'project.open': 'Open Game Project',
      'project.status': 'Project Status',
      'project.unrecognized': 'Unrecognized',
      'project.hint': 'Select a game directory. The engine will be detected automatically.',
      'project.scanDataRoots': 'Scan Text Locations',
      'project.scanDataRootsDone': 'Text data directories found: {count}',
      'project.scanDataRootsEmpty': 'No scannable data directory was found. Please check the project structure.',
      'project.scanDataRootsFailed': 'Failed to scan text locations: {message}',
      'project.scanDataRootsMissing': 'Open a project before scanning text locations.',
      'project.scanningDataRoots': 'Scanning text directories…',
      'project.recognized': 'Recognized',
      'project.recognizedHint': 'Project structure recognized. You can proceed to import and translate.',
      'project.dataRootsFound': 'Found {count} text directories',
      'project.dataRootsEmpty': 'No text directories found',
      'project.statusLoaded': 'Project loaded',
      'project.statusDraft': 'Draft loaded',
      'project.statusLoading': 'Loading project…',
      'project.ready': 'Project ready: {path}',
      'trace.projectStatus': 'Project status trace',
      'trace.openProject': 'Open project',
      'trace.loadDraftBtn': 'Load draft button',
      'trace.prepareRead': 'Preparing to read: {path}',
      'trace.callSystemDirPicker': 'Calling system directory picker',
      'trace.userCancel': 'User cancelled selection',
      'trace.pickResult': 'Pick result rootDir={rootDir}, engine={engine}',
      'trace.mainProcessReturn': 'Main process returned entries={entries}, warnings={warnings}',
      'trace.startPickDraftFile': 'Starting draft file selection',
      'trace.draftOpened': 'Opened {path}',
      'common.processing': 'Processing',
      'common.unknownError': 'Unknown error',
      'common.operationFailed': 'Operation failed',
      'draft.loadFailed': 'Failed to load draft',
      'draft.loaded': 'Draft loaded: {path}',
      'features.title': 'Key Features',
      'features.import': 'Import MV / MZ project resources',
      'features.extract': 'Extract dialogues, choices, and name lists',
      'features.glossary': 'Local glossary storage with export support',
      'features.export': 'Export draft and localization patch directory',
      'glossary.title': 'Glossary',
      'glossary.panelHint': 'Open the glossary manager to create, import, export, or delete glossaries.',
      'glossary.manage': 'Manage Glossary',
      'workspace.title': 'Workspace',
      'workspace.exportDraft': 'Export Draft',
      'workspace.draftLoad': 'Load Draft',
      'workspace.settings': 'Settings',
      'workspace.clearTexts': 'Clear Current JSON Translations',
      'workspace.clearConfirm': 'This will clear all translations in the current JSON file and mark entries as untranslated. Export a draft first if needed. Continue?',
      'workspace.export': 'Export Patch',
      'workspace.noProject': 'No project loaded',
      'workspace.load': 'Export Draft',
      'workspace.ai': 'AI Assist',
      'selector.file': 'JSON File',
      'selector.search': 'Search',
      'selector.searchPlaceholder': 'Filter by keyword',
      'selector.title': 'Bilingual Editor',
      'selector.hint': 'Edit source and translation side by side with glossary and assisted translation',
      'editor.source': 'Source',
      'editor.target': 'Translation',
      'editor.targetPlaceholder': 'Enter translation',
      'stats.groups': 'Text Groups',
      'stats.progress': 'Total / Translated',
      'stats.translated': 'Translated',
      'stats.hits': 'Glossary Hits',
      'progress.global': 'Project Progress',
      'progress.currentFile': 'Current File Progress',
      'progress.file': 'File Progress',
      'progress.translated': 'Translated',
      'progress.pending': 'Pending',
      'progress.reviewed': 'Reviewed',
      'progress.warning': 'Warnings',
      'progress.lastPosition': 'Last Translation Position',
      'progress.continueLast': 'Continue Last Translation',
      'progress.gotoLast': 'Go to Last Position',
      'progress.nextPending': 'Next Pending',
      'progress.previousPending': 'Previous Pending',
      'progress.filterPending': 'Pending Only',
      'progress.filterWarnings': 'Warnings Only',
      'progress.filterContextual': 'Contextual Only',
      'progress.filterAtomic': 'Atomic Only',
      'progress.noLastPosition': 'No previous translation position',
      'progress.noPending': 'No pending entries',
      'progress.summary': '{translated}/{total} · {percent}%',
      'progress.toggleStatus': 'Toggle translation status',
      'context.viewMode': 'Translation Mode',
      'context.singleMode': 'Single Entry Mode',
      'context.groupMode': 'Context Group Mode',
      'context.scrollSync': 'Sync scroll position',
      'context.scrollSyncTitle': 'When checked, scroll positions of Single Entry and Context Group translation modes stay in sync; enabling the checkbox aligns the inactive mode\'s position to the currently active one.',
      'context.noGroups': 'No context groups in the current file',
      'context.groupTargetPlaceholder': 'Enter the overall translation for this context group',
      'context.groupShort': 'Context Group',
      'context.groupSummary': 'Context Group · {count} entries · {keys}',
      'context.groupEmpty': 'Tick entries below to compose a context group, then translate as a whole and auto-split back by \\N markers.',
      'context.sourcePlaceholder': 'Edit this area to adjust segmentation. Use \\N to mark splits (count must match the translation segments).',
      'context.targetPlaceholder': 'Enter the overall translation for this context group. Use \\N to mark line breaks.',
      'context.previewLabel': 'Translation preview (click separators to insert / remove \\N markers; you can also type \\N above)',
      'context.previewInsert': 'Click to insert \\N marker',
      'context.previewRemove': 'Click to remove \\N marker',
      'context.previewEmptyLine': '(empty line)',
      'context.splitHint': 'When you click "AI Translate Group": for LLM providers (DeepSeek / OpenAI / Claude) a JSON structured protocol is auto-enabled (numbered key-value alignment with response_format forcing JSON); for traditional translators (Baidu / Google) the \\N text protocol is used. RPG Maker codes (\\N[1] / \\V[3] / \\C[10] etc.) are masked as {{RPG_CODE_n}} before sending and restored after. Mismatched segment counts trigger up to 2 diagnostic retries.',
      'context.aiTranslateGroup': 'AI Translate Group',
      'context.aiTranslateGroupTitle': 'Send the edited source text to AI; the program wraps the segmentation protocol, protects control codes, validates segment count and retries when needed.',
      'context.applyToSelected': 'Apply to Selected',
      'context.clearSelection': 'Clear Selection',
      'context.listFilterPlaceholder': 'Search candidates by source / key…',
      'context.backToTop': 'Back to Top',
      'context.backToTopTitle': 'Scroll the candidate list back to the top',
      'context.sourceEmpty': 'Source box is empty, cannot translate',
      'context.aiCalling': 'Calling AI ({provider})…',
      'context.aiRetrying': 'Segment mismatch ({actual}/{expected}), retrying diagnostically {attempt}/{max}…',
      'context.aiSegmentCountWarn': 'Hint: source textarea has {input} segments but {expected} entries are selected; output will be constrained to {expected} segments.',
      'context.aiSuccess': 'Translated by {provider}, back-filled {count}/{expected} segments',
      'context.aiSuccessWithRetry': 'Translated by {provider}, back-filled {count}/{expected} segments (aligned after {retried} retries)',
      'context.aiFailRetained': 'Group translation failed: {reason} (after {attempts} attempts segment count never matched; best-effort output is shown in the target box — adjust manually and click "Apply to Selected")',
      'context.aiFailEmpty': 'Group translation failed: {reason}',
      'context.aiTraceSuccess': 'Aligned {count}/{expected}; attempts={attempts}; reason={reason}',
      'context.aiTracePending': 'Translate with {provider}: {count} entries (control-code protection + retry)',
      'context.aiSegmentMismatch': 'Translation segment count mismatch (actual {actual}, expected {expected})',
      'context.aiRetryExhausted': '{reason}; after {max} diagnostic retries the count never aligned',
      'context.aiTraceLabel': 'Group Translation',
      'context.aiTradBatchProgress': 'Per-segment translation ({current}/{total})…',
      'context.aiTradBatchFailed': 'Segment {index} failed: {reason}',
      'progress.jumpFail': 'Target position no longer exists',
      'progress.gotoLastDone': '{action} → {file} #{index}',
      'textClass.contextual': 'Contextual Text',
      'textClass.atomic': 'Atomic Term',
      'textClass.mixed': 'Mixed Text',
      'textClass.unknown': 'Unknown Type',
      'textType.dialogue-line': 'Dialogue Line',
      'textType.dialogue-block': 'Dialogue Group',
      'textType.long-description': 'Long Text',
      'textType.choice-option': 'Choice',
      'textType.actor-name': 'Actor Name',
      'textType.actor-description': 'Actor Description',
      'textType.enemy-name': 'Enemy Name',
      'textType.enemy-description': 'Enemy Description',
      'textType.item-name': 'Item Name',
      'textType.item-description': 'Item Description',
      'textType.items-description': 'Item Description',
      'textType.weapon-name': 'Weapon Name',
      'textType.weapon-description': 'Weapon Description',
      'textType.weapons-description': 'Weapon Description',
      'textType.armor-name': 'Armor Name',
      'textType.armor-description': 'Armor Description',
      'textType.armors-description': 'Armor Description',
      'textType.skill-name': 'Skill Name',
      'textType.skill-description': 'Skill Description',
      'textType.skills-description': 'Skill Description',
      'textType.state-name': 'State Name',
      'textType.state-description': 'State Description',
      'textType.states-description': 'State Description',
      'textType.class-name': 'Class Name',
      'textType.class-description': 'Class Description',
      'textType.classes-description': 'Class Description',
      'textType.map-name': 'Map Name',
      'textType.system-command': 'System Command',
      'textType.system-message': 'System Message',
      'textType.system-title': 'System Title',
      'textType.currency-unit': 'Currency Unit',
      'textType.event-message': 'Event Message',
      'textType.speaker': 'Speaker',
      'textType.plugin-text': 'Plugin Text',
      'textType.generic-text': 'Generic Text',
      'glossary.hitCount': 'Glossary Hits: {count}',
      'glossary.insertMode': 'Insert Mode',
      'glossary.insertCursor': 'Insert at cursor',
      'glossary.insertReplace': 'Replace selection',
      'glossary.insertAppend': 'Append to end',
      'glossary.insertAll': 'Insert all',
      'glossary.insertOne': 'Insert: {source} → {target}',
      'glossary.insertAllDone': 'Inserted all glossary terms: {count}',
      'glossary.insertOneDone': 'Inserted glossary term into translation: {source}',
      'entry.aiTranslate': 'AI Translate',
      'entry.aiTranslateTitle': 'Translate this entry with the currently selected assist provider',
      'entry.preview': 'Preview',
      'entry.previewTitle': 'Preview this translation in the game',
      'entry.previewEmpty': 'Translation is empty',
      'entry.previewPending': 'Launching game preview...',
      'entry.previewApiMissing': 'Preview API unavailable',
      'entry.previewStarted': 'Preview started (PID: {pid})',
      'entry.repreviewStarted': 'Preview position updated (PID: {pid})',
      'entry.previewFailed': 'Failed to start preview',
      'entry.previewGroupTitle': 'Preview the whole group using the first line as entry point',
      'entry.previewNoSibling': 'No more adjacent lines in this event',
      'preview.embeddedTitle': 'Game Preview',
      'preview.embeddedHint': 'The game window will be embedded below. Close the game or click the button to restore backups.',
      'preview.buttonPrev': 'Prev',
      'preview.buttonNext': 'Next',
      'preview.buttonTitle': 'Title',
      'preview.close': 'Close Preview',
      'preview.tvPlaceholder': 'Click the Preview button on a translation row to see the game scene here',
      'preview.tvPower': 'Power',
      'common.confirm': 'Confirm',
      'common.cancel': 'Cancel',
      'common.edit': 'Edit',
      'common.delete': 'Delete',
      'common.none': 'No items',
      'common.aiPending': 'Calling AI model...',
      'common.aiSaved': 'AI settings saved.',
      'common.aiSaveFailed': 'Failed to save AI settings.',
      'common.aiTestFail': 'AI test failed.',
      'common.aiTestSuccess': 'AI test succeeded.',
      'common.aiTestEmpty': 'AI test returned no result.',
      'ai.status': 'Choose a translation mode to start.',
      'settings.language': 'Interface Language',
      'settings.themeMode': 'Color Mode',
      'settings.themeSystem': 'System',
      'settings.themeDark': 'Dark',
      'settings.themeLight': 'Light',
      'settings.themePalette': 'Color Palette',
      'settings.paletteViolet': 'Violet',
      'settings.paletteBlue': 'Blue',
      'settings.paletteEmerald': 'Emerald',
      'settings.paletteRose': 'Rose',
      'settings.paletteAmber': 'Amber',
      'settings.paletteSlate': 'Slate',
      'settings.backgroundImage': 'Background Image',
      'settings.backgroundImagePlaceholder': 'Enter image path or URL, leave empty for solid color',
      'settings.backgroundHint': 'Supports local paths or remote URLs. Clear to restore solid background.',
      'settings.closeBehavior': 'Close Button Behavior',
      'settings.closeBehaviorTray': 'Minimize to system tray',
      'settings.closeBehaviorExit': 'Exit immediately',
      'settings.closeBehaviorHint': 'If you choose "Minimize to tray", clicking the top-right X will hide the app to the system tray instead of quitting. Open the tray icon again to restore the window. If you choose "Exit immediately", clicking X will close the app normally.',
      'settings.previewGroupTitle': 'In-Game Preview',
      'settings.enableGamePreview': 'Enable in-game quick preview (only shown for RPG Maker MV/MZ projects)',
      'settings.enableGamePreviewHint': 'When turned off, the Preview button in single entry and context group modes will be hidden.',
      'settings.previewWindowMode': 'Preview window mode',
      'settings.previewWindowModePopup': 'Popup window (Game.exe)',
      'settings.previewWindowModeEmbedded': 'Embedded at bottom of main window',
      'settings.showPreviewNotification': 'Show "Text Content Preview Mode" hint in game when launching preview',
      'settings.previewNotificationPosition': 'Hint position',
      'settings.previewNotificationPositionTopLeft': 'Top left',
      'settings.previewNotificationPositionTopCenter': 'Top center',
      'settings.previewNotificationPositionTopRight': 'Top right',
      'settings.previewNotificationPositionBottomLeft': 'Bottom left',
      'settings.previewNotificationPositionBottomCenter': 'Bottom center',
      'settings.previewNotificationPositionBottomRight': 'Bottom right',
      'settings.pickBackground': 'Browse Local Image',
      'settings.previewBackground': 'Preview Background',
      'settings.applyBackground': 'Apply Without Saving',
      'settings.clearBackground': 'Clear Background',
      'settings.resetTheme': 'Restore Defaults',
      'settings.previewTitle': 'Background Preview',
      'settings.previewEmpty': 'No background image set',
      'settings.tabUI': 'Interface',
      'settings.tabTraditional': 'Traditional',
      'settings.tabLLM': 'LLM Translation',
      'settings.titleUI': 'Interface Settings',
      'settings.titleTraditional': 'Traditional Translation Settings',
      'settings.titleLLM': 'LLM Translation Settings',
      'settings.save': 'Save Settings',
      'settings.close': 'Close',
      'settings.baiduAppId': 'Baidu App ID',
      'settings.baiduAppIdPlaceholder': 'Your Baidu App ID',
      'settings.baiduSecret': 'Baidu Secret Key',
      'settings.baiduSecretPlaceholder': 'Your Baidu Secret Key',
      'settings.googleApiKey': 'Google API Key',
      'settings.googleApiKeyPlaceholder': 'Your Google API Key',
      'settings.sourceLang': 'Source Language',
      'settings.sourceLangPlaceholder': 'auto',
      'settings.targetLang': 'Target Language',
      'settings.targetLangPlaceholder': 'zh-CN',
      'settings.traditionalHint': 'Choose a traditional translation service. Baidu requires App ID and Secret; Google requires an API Key.',
      'settings.llmHint': 'Best for high-quality, character-consistent, and stylized translations.',
      'glossary.currentProject': 'Current Project',
      'glossary.emptyHint': 'Glossary is empty. Add terms below.',
      'glossary.termCountHint': 'This glossary contains {count} term(s).',
      'glossary.confirmDeleteTerm': 'Delete term "{source}"?',
      'glossary.confirmDeleteGlossary': 'Delete glossary "{name}"?',
      'glossary.termAdded': 'Term added: {source} → {target}',
      'glossary.termUpdated': 'Term updated: {source} → {target}',
      'glossary.termDeleted': 'Term deleted: {source}',
      'glossary.created': 'Glossary created: {name}',
      'glossary.createdAt': 'Glossary created: {name} at {path}',
      'glossary.createCanceled': 'New glossary cancelled.',
      'glossary.createFailed': 'Failed to create glossary',
      'glossary.saveAsApiMissing': 'Save-as API not registered',
      'glossary.exportApiMissing': 'Export API not registered',
      'glossary.exportCanceled': 'Export cancelled.',
      'glossary.exported': 'Glossary exported: {name}{path}',
      'glossary.imported': 'Glossary imported: {name}',
      'glossary.deleted': 'Glossary deleted: {name}',
      'glossary.saving': 'Saving glossary…',
      'glossary.creating': 'Creating glossary…',
      'glossary.exporting': 'Exporting glossary…',
      'glossary.importing': 'Importing glossary…',
      'glossary.renaming': 'Renaming glossary: {from} → {to}',
      'glossary.loadProjectFirst': 'Please open a project first',
      'glossary.importApiMissing': 'Import API not registered',
      'glossary.saveFailed': 'Failed to save glossary',
      'glossary.listInitFailed': 'Failed to initialize glossary list',
      'glossary.listRefreshFailed': 'Failed to refresh glossary list',
      'glossary.exportFailed': 'Export failed',
      'glossary.importFailed': 'Import failed',
      'glossary.deleteFailed': 'Delete failed',
      'validation.tooManyLines': '{actual}/{max} lines',
      'validation.lineTooLong': 'Line {line}: {actual}/{max} chars',
      'validation.missingControlCodes': 'Missing control codes: {codes}',
      'ai.defaultSystemPrompt': 'You are a professional RPG Maker game localization assistant. Please translate the source text naturally and accurately into Simplified Chinese.',
      'ai.providerBaidu': 'Baidu Translate',
      'ai.providerGoogle': 'Google Translate',
      'ai.providerDeepseek': 'DeepSeek',
      'ai.providerKimi': 'Kimi (Moonshot AI)',
      'ai.providerGemini': 'Gemini',
      'ai.providerClaude': 'Claude / Anthropic',
      'ai.providerCustom': 'Custom OpenAI-Compatible API',
      'ai.apiKeyPlaceholder': 'Your API Key',
      'ai.baseUrlPlaceholder': 'Endpoint URL (e.g. https://api.deepseek.com/chat/completions)',
      'ai.kimiTutorialTitle': 'Kimi (Moonshot AI) Setup Guide',
      'ai.kimiStep1': '1. Kimi runs two independent endpoints and their API keys are NOT interchangeable. Pick one: (a) International: sign in at platform.kimi.ai, use base_url https://api.moonshot.ai/v1. (b) China: sign in at platform.moonshot.cn, use base_url https://api.moonshot.cn/v1. Mixing a key with the wrong endpoint returns HTTP 401.',
      'ai.kimiStep2': '2. In the matching console → "API Keys" → "Create API Key", copy the sk-... value and paste it into the API Key field above (the eye icon toggles visibility).',
      'ai.kimiStep3': '3. Pick the matching endpoint: https://api.moonshot.ai/v1 (international) or https://api.moonshot.cn/v1 (China). The /v1 suffix is required; the app appends /chat/completions automatically.',
      'ai.kimiStep4': '4. For everyday translation, pick moonshot-v1-8k (cheapest 8K context). For longer text, use moonshot-v1-32k / moonshot-v1-128k. For top quality, use kimi-k2.6.',
      'ai.kimiStep5': '5. Deprecated: kimi-latest (retired 2026-01-28) and the kimi-k2-*-preview family (retired 2026-05-25). Do not use them.',
      'ai.kimiStep6': '6. After saving, click "Test LLM translation" to verify. A 401 usually means the key was created against the OTHER endpoint — recheck source and balance.',
      'ai.toggleKeyShow': 'Show key',
      'ai.toggleKeyHide': 'Hide key',
      'ai.deepseekV4Flash': 'deepseek-v4-flash (official recommended, non-thinking)',
      'ai.deepseekV4Pro': 'deepseek-v4-pro (official recommended, thinking)',
      'ai.deepseekChat': 'deepseek-chat (legacy name, will be deprecated)',
      'ai.deepseekReasoner': 'deepseek-reasoner (legacy name, will be deprecated)',
      'app.version': '· 1.2.0',
      'language.zhCN': '简体中文',
      'language.en': 'English',
      'language.ja': '日本語',
      'workspace.applyWritebackTitle': 'Write current translations back to new JSON without overwriting original files (outputs to localization_patch/data/)',
      'workspace.stopPreview': 'Stop Game Preview',
      'workspace.stopPreviewTitle': 'Force stop the game preview and restore original JSON backups',
      'workspace.stoppingPreview': 'Stopping game preview and restoring backups…',
      'workspace.returnToTitle': 'Return to Title',
      'workspace.returnToTitleTitle': 'Return to the title screen without closing the game (F12)',
      'workspace.returningToTitle': 'Returning to title screen…',
      'workspace.returnedToTitle': 'Returned to title screen',
      'workspace.returnToTitleFailed': 'Failed to return to title',
      'workspace.previewStopped': 'Game preview stopped',
      'workspace.previewStoppedRestored': 'Restored {files} preview backup file(s)',
      'workspace.previewStopFailed': 'Failed to stop preview',
      'workspace.previewProcessExited': 'Game preview process ended, backups restored',
      'project.previewBackupsRestored': 'Detected leftover preview backups from a crash and restored {files} file(s)',
      'ai.modelPlaceholder': 'Model name (e.g. deepseek-chat)',
      'ai.promptPlaceholder': 'System prompt (optional)',
      'ai.prompt': 'System Prompt',
      'trace.project': 'Project',
      'trace.aiTranslate': 'AI Translation',
      'trace.traditionalTranslate': 'Traditional Translation',
      'trace.notice': 'Notice',
      'trace.status': 'Status',
      'trace.assistPlatform': 'AI Assist Platform',
      'trace.providerSwitched': 'Switched to {provider}',
      'trace.uiSettings': 'UI Settings',
      'trace.uiSettingsSaved': 'UI settings saved.',
      'trace.backgroundImage': 'Background Image',
      'trace.selectFailed': 'Selection failed',
      'trace.defaultThemeRestored': 'Default appearance restored',
      'trace.waiting': 'Waiting for operation…',
      'trace.initFailed': 'Initialization failed',
      'trace.unknownError': 'Unknown error',
      'trace.aiSettings': 'LLM Translation Settings',
      'trace.aiTest': 'LLM Translation Test',
      'trace.traditionalSettings': 'Traditional Translation Settings',
      'trace.traditionalTest': 'Traditional Translation Test',
      'app.copyright': '© 2026 RPG Localization Workbench. All rights reserved.',
    
      'action.openProjectFolder': 'Open project folder',
      'action.loadProjectTexts': 'Load project texts',
      'action.saveTranslatorSettings': 'Save translator settings',
      'action.testTranslatorSettings': 'Test translator settings',
      'action.aiTranslate': 'AI translate',
      'action.previewInGame': 'Preview in game',
      'action.repreviewInGame': 'Update preview position',
      'action.returnToTitle': 'Return to title',
      'action.stopPreview': 'Stop game preview',
      'action.saveProjectLastPosition': 'Save translation position',
      'action.loadProjectProgressState': 'Load project progress',
      'action.getUiSettings': 'Get UI settings',
      'action.saveUiSettings': 'Save UI settings',
      'trace.actionStart': 'Action started',
      'trace.actionSuccess': 'Action completed',
      'trace.actionFailed': 'Action failed',
      'error.projectRequired': 'Please open and load a project before {action}',
      'error.saveDraftApiMissing': 'Draft export API not injected',
      'error.exportDraftFailed': 'Export draft failed',
      'error.exportPatchApiMissing': 'Patch export API not injected',
      'error.exportPatchFailed': 'Export patch failed',
      'error.writebackApiMissing': 'Writeback API not injected',
      'error.writebackFailed': 'Writeback failed',
      'action.exportDraft': 'Export draft',
      'action.exportPatch': 'Export patch',
      'action.writebackJson': 'Write back JSON',
      'export.draftPending': 'Exporting draft…',
      'export.draftSuccess': 'Draft export completed',
      'export.draftError': 'Draft export failed',
      'export.patchPending': 'Exporting patch…',
      'export.patchSuccess': 'Patch export completed',
      'export.patchError': 'Patch export failed',
      'trace.writebackClicked': 'Clicked write back to game JSON',
      'action.openPatchDir': 'Open patch directory',
      'error.noPatchDir': 'No patch directory to open',
      'error.openDirApiMissing': 'Open directory API not injected',
      'action.openingPatchDir': 'Opening patch directory…',
      'action.patchDirOpened': 'Patch directory opened',
      'action.openPatchDirFailed': 'Failed to open patch directory',
      'writeback.summary': 'Wrote back {count} JSON files ({errors} errors)',
    },
    ja: {
      'app.title': 'RPG ローカライズワークベンチ',
      'app.subtitle': 'リリース · 抽出 · 校正 · 用語集 · エクスポート',
      'welcome.title': 'ローカライズワークベンチへようこそ',
      'welcome.description': 'RPG Maker プロジェクトをインポートし、テキストを抽出・用語を管理・パッチを生成します。',
      'welcome.start': '翻訳を開始',
      'welcome.demo': 'デモを見る',
      'project.open': 'ゲームプロジェクトを開く',
      'project.status': 'プロジェクト状態',
      'project.unrecognized': '未認識',
      'project.hint': 'ゲームディレクトリを選択してください。エンジンを自動検出します。',
      'project.scanDataRoots': 'テキスト位置をスキャン',
      'project.scanDataRootsDone': '検出されたテキストディレクトリ数：{count}',
      'project.scanDataRootsEmpty': 'スキャン可能なデータディレクトリが見つかりません。プロジェクト構造を確認してください。',
      'project.scanDataRootsFailed': 'テキスト位置のスキャンに失敗しました：{message}',
      'project.scanDataRootsMissing': 'テキスト位置をスキャンする前にプロジェクトを開いてください。',
      'project.scanningDataRoots': 'テキストディレクトリをスキャン中…',
      'features.title': '主な機能',
      'features.import': 'MV / MZ プロジェクトリソースのインポート',
      'features.extract': '会話・選択肢・名詞リストの自動抽出',
      'features.glossary': '用語集のローカル保存とエクスポート',
      'features.export': '草稿とローカライズパッチの出力',
      'glossary.title': '用語集',
      'glossary.panelHint': '用語集マネージャーを開いて作成・インポート・エクスポート・削除が可能です。',
      'glossary.manage': '用語集を管理',
      'workspace.title': 'ワークスペース',
      'workspace.exportDraft': '草稿を出力',
      'workspace.draftLoad': '草稿を読み込む',
      'workspace.settings': '設定',
      'workspace.clearTexts': '現在の JSON 翻訳をクリア',
      'workspace.clearConfirm': 'バイリンガルエディターで表示中の JSON ファイルの全翻訳をクリアし、エントリを未翻訳にします。必要なら先に草稿をエクスポートしてください。続行しますか？',
      'workspace.export': 'パッチを出力',
      'workspace.noProject': 'プロジェクト未読み込み',
      'workspace.load': '草稿を出力',
      'workspace.ai': 'AI 翻訳補助',
      'selector.file': 'JSON ファイル',
      'selector.search': '検索',
      'selector.searchPlaceholder': 'キーワードで絞り込む',
      'selector.title': 'バイリンガルエディター',
      'selector.hint': '原文と翻訳を並べて編集。用語集と翻訳補助に対応',
      'editor.source': '原文',
      'editor.target': '翻訳',
      'editor.targetPlaceholder': '翻訳を入力',
      'stats.groups': 'テキストグループ',
      'stats.progress': '合計 / 翻訳済み',
      'stats.translated': '翻訳済み',
      'stats.hits': '用語ヒット',
      'progress.global': 'プロジェクト進捗',
      'progress.currentFile': '現在のファイル進捗',
      'progress.file': 'ファイル進捗',
      'progress.translated': '翻訳済み',
      'progress.pending': '未翻訳',
      'progress.reviewed': '校正済み',
      'progress.warning': '警告',
      'progress.lastPosition': '前回の翻訳位置',
      'progress.continueLast': '前回の続きから翻訳',
      'progress.gotoLast': '前回位置へ移動',
      'progress.nextPending': '次の未翻訳',
      'progress.previousPending': '前の未翻訳',
      'progress.filterPending': '未翻訳のみ',
      'progress.filterWarnings': '警告のみ',
      'progress.filterContextual': '文脈テキストのみ',
      'progress.filterAtomic': '独立語句のみ',
      'progress.noLastPosition': '前回の翻訳位置はありません',
      'progress.noPending': '未翻訳項目はありません',
      'progress.summary': '{translated}/{total} · {percent}%',
      'progress.toggleStatus': '翻訳済み/未翻訳を切り替える',
      'context.viewMode': '翻訳モード',
      'context.singleMode': '単一項目モード',
      'context.groupMode': '文脈グループモード',
      'context.scrollSync': 'スクロール位置を同期',
      'context.scrollSyncTitle': 'チェックすると単一項目翻訳モードと文脈グループ翻訳モードのスクロール位置が同期されます。チェックした瞬間、非アクティブモードの位置は現在のモードの位置に合わせられます。',
      'context.noGroups': '現在のファイルには文脈グループがありません',
      'context.groupTargetPlaceholder': 'この文脈グループ全体の翻訳を入力',
      'context.groupShort': '文脈グループ',
      'context.groupSummary': '文脈グループ · {count} 件 · {keys}',
      'context.groupEmpty': '下のエントリを選択して文脈グループを構成すると、まとめて翻訳し \\N マーカーで各行に自動分割できます。',
      'context.sourcePlaceholder': 'この領域を手動編集して文章の区切りを調整できます。\\N を使って分段マーカーを挿入（下の翻訳の段数と一致させてください）',
      'context.targetPlaceholder': 'この文脈グループ全体の翻訳を入力。\\N で素早く改行できます',
      'context.previewLabel': '翻訳プレビュー（行間の区切りをクリックして \\N マーカーを挿入 / 削除；上の入力欄に直接 \\N を入力することも可）',
      'context.previewInsert': 'クリックして \\N マーカーを挿入',
      'context.previewRemove': 'クリックして \\N マーカーを削除',
      'context.previewEmptyLine': '（空行）',
      'context.splitHint': '「AI でグループ翻訳」をクリックすると、DeepSeek / OpenAI / Claude などの LLM では JSON 構造化プロトコルが自動有効化され（入出力ともに番号付きキー値で一対一対応、response_format で JSON 強制出力）；百度 / Google などの従来型翻訳では \\N テキストプロトコルを使用。RPG Maker の制御コード（\\N[1] / \\V[3] / \\C[10] など）は {{RPG_CODE_n}} に一時置換して送信し、戻り値で原形に復元。段数不一致時は最大 2 回まで自動診断リトライ。',
      'context.aiTranslateGroup': 'AI でグループ翻訳',
      'context.aiTranslateGroupTitle': '原文 textarea で編集した全体を AI に送信。分段プロトコルの包装、制御コード保護、段数検証、必要に応じた自動リトライを行います',
      'context.applyToSelected': '選択項目に適用',
      'context.clearSelection': '選択をクリア',
      'context.listFilterPlaceholder': '候補エントリを原文 / key で検索…',
      'context.backToTop': '一番上へ',
      'context.backToTopTitle': '候補エントリリストの一番上へスクロール',
      'context.sourceEmpty': '原文ボックスが空です。翻訳できません',
      'context.aiCalling': 'AI 呼び出し中（{provider}）…',
      'context.aiRetrying': '段数不一致（{actual}/{expected}）、診断付きリトライ中 {attempt}/{max}…',
      'context.aiSegmentCountWarn': 'ヒント：原文 textarea の分段数 {input} ≠ 選択エントリ数 {expected}、{expected} 段の制約で出力します',
      'context.aiSuccess': '{provider} でグループ翻訳完了、{count}/{expected} 段を精密に書き戻しました',
      'context.aiSuccessWithRetry': '{provider} でグループ翻訳完了、{count}/{expected} 段を精密に書き戻しました（{retried} 回のリトライ後に整合）',
      'context.aiFailRetained': 'グループ翻訳失敗：{reason}（合計 {attempts} 回呼び出し、段数が整合しませんでした；ベストエフォートの結果を翻訳ボックスに表示しました。手動で調整して「選択項目に適用」をクリックしてください）',
      'context.aiFailEmpty': 'グループ翻訳失敗：{reason}',
      'context.aiTraceSuccess': '整合 {count}/{expected}；attempts={attempts}；reason={reason}',
      'context.aiTracePending': '{provider} で翻訳：{count} 件（制御コード保護 + リトライ）',
      'context.aiSegmentMismatch': '翻訳の段数が一致しません（実際 {actual} 段、要求 {expected} 段）',
      'context.aiRetryExhausted': '{reason}；診断付きリトライを {max} 回繰り返しましたが整合しませんでした',
      'context.aiTraceLabel': 'グループ翻訳',
      'context.aiTradBatchProgress': '逐次翻訳中（{current}/{total}）…',
      'context.aiTradBatchFailed': 'セグメント {index} の翻訳失敗：{reason}',
      'progress.jumpFail': 'ジャンプ先が存在しません',
      'progress.gotoLastDone': '{action} → {file} #{index}',
      'textClass.contextual': '文脈テキスト',
      'textClass.atomic': '独立語句',
      'textClass.mixed': '混合テキスト',
      'textClass.unknown': '不明な種類',
      'textType.dialogue-line': '会話行',
      'textType.dialogue-block': '会話グループ',
      'textType.long-description': '長文',
      'textType.choice-option': '選択肢',
      'textType.actor-name': 'キャラクター名',
      'textType.actor-description': 'キャラクター説明',
      'textType.enemy-name': '敵名',
      'textType.enemy-description': '敵説明',
      'textType.item-name': 'アイテム名',
      'textType.item-description': 'アイテム説明',
      'textType.items-description': 'アイテム説明',
      'textType.weapon-name': '武器名',
      'textType.weapon-description': '武器説明',
      'textType.weapons-description': '武器説明',
      'textType.armor-name': '防具名',
      'textType.armor-description': '防具説明',
      'textType.armors-description': '防具説明',
      'textType.skill-name': 'スキル名',
      'textType.skill-description': 'スキル説明',
      'textType.skills-description': 'スキル説明',
      'textType.state-name': 'ステート名',
      'textType.state-description': 'ステート説明',
      'textType.states-description': 'ステート説明',
      'textType.class-name': '職業名',
      'textType.class-description': '職業説明',
      'textType.classes-description': '職業説明',
      'textType.map-name': 'マップ名',
      'textType.system-command': 'システムコマンド',
      'textType.system-message': 'システムメッセージ',
      'textType.system-title': 'システムタイトル',
      'textType.currency-unit': '通貨単位',
      'textType.event-message': 'イベントメッセージ',
      'textType.speaker': '話者',
      'textType.plugin-text': 'プラグインテキスト',
      'textType.generic-text': '汎用テキスト',
      'glossary.hitCount': '用語ヒット {count} 件',
      'glossary.insertMode': '挿入方法',
      'glossary.insertCursor': 'カーソル位置に挿入',
      'glossary.insertReplace': '選択範囲を置換',
      'glossary.insertAppend': '末尾に追加',
      'glossary.insertAll': 'すべて挿入',
      'glossary.insertOne': '挿入：{source} → {target}',
      'glossary.insertAllDone': 'すべての用語を挿入しました：{count} 件',
      'glossary.insertOneDone': '用語を翻訳文に挿入しました：{source}',
      'entry.aiTranslate': 'AI 翻訳',
      'entry.aiTranslateTitle': '現在選択中の補助翻訳プロバイダでこの項目を翻訳します',
      'entry.preview': 'プレビュー',
      'entry.previewTitle': 'ゲーム内でこの翻訳をプレビュー',
      'entry.previewEmpty': '翻訳が空です',
      'entry.previewPending': 'ゲームプレビューを起動中…',
      'entry.previewApiMissing': 'プレビューAPIがありません',
      'entry.previewStarted': 'プレビュー開始 (PID: {pid})',
      'entry.repreviewStarted': 'プレビュー位置を更新しました (PID: {pid})',
      'entry.previewFailed': 'プレビューの起動に失敗しました',
      'entry.previewGroupTitle': '先頭行をエントリポイントとしてグループ全体をプレビュー',
      'entry.previewNoSibling': 'このイベントに隣接する文はこれ以上ありません',
      'preview.embeddedTitle': 'ゲームプレビュー',
      'preview.embeddedHint': 'ゲームウィンドウが下の領域に埋め込まれます。ゲームを閉じるか、右のボタンをクリックするとバックアップが復元されます。',
      'preview.buttonPrev': '前へ',
      'preview.buttonNext': '次へ',
      'preview.buttonTitle': 'タイトル',
      'preview.close': 'プレビューを閉じる',
      'preview.tvPlaceholder': '訳文行の「プレビュー」ボタンを押すと、ゲーム画面がここに表示されます',
      'preview.tvPower': '電源',
      'common.confirm': '確認',
      'common.cancel': 'キャンセル',
      'common.edit': '編集',
      'common.delete': '削除',
      'common.none': 'アイテムなし',
      'common.aiPending': 'AI モデルを呼び出し中...',
      'common.aiSaved': 'AI 設定を保存しました。',
      'common.aiSaveFailed': 'AI 設定の保存に失敗しました。',
      'common.aiTestFail': 'AI テストに失敗しました。',
      'common.aiTestSuccess': 'AI テストに成功しました。',
      'common.aiTestEmpty': 'AI テストの結果が空です。',
      'ai.status': '翻訳モードを選択して開始してください。',
      'settings.language': 'インターフェース言語',
      'settings.themeMode': '配色モード',
      'settings.themeSystem': 'システムに従う',
      'settings.themeDark': 'ダーク',
      'settings.themeLight': 'ライト',
      'settings.themePalette': 'カラーパレット',
      'settings.paletteViolet': 'バイオレット',
      'settings.paletteBlue': 'ブルー',
      'settings.paletteEmerald': 'エメラルド',
      'settings.paletteRose': 'ローズ',
      'settings.paletteAmber': 'アンバー',
      'settings.paletteSlate': 'スレート',
      'settings.backgroundImage': '背景画像',
      'settings.backgroundImagePlaceholder': '画像パスまたは URL を入力（空で単色背景）',
      'settings.backgroundHint': 'ローカルパスまたはリモート URL をサポート。空にすると単色に戻ります。',
      'settings.closeBehavior': '閉じるボタンの動作',
      'settings.closeBehaviorTray': 'タスクトレイに最小化',
      'settings.closeBehaviorExit': 'すぐに終了',
      'settings.closeBehaviorHint': '「タスクトレイに最小化」を選ぶと、右上の X を押しても終了せず、システムトレイに隠れます。トレイアイコンから再表示できます。「すぐに終了」を選ぶと、X を押したときに通常どおり終了します。',
      'settings.previewGroupTitle': 'ゲーム内プレビュー',
      'settings.enableGamePreview': 'ゲーム内クイックプレビューを有効にする（RPG Maker MV/MZ プロジェクトのみ表示）',
      'settings.enableGamePreviewHint': 'オフにすると、単一項目モードと文脈グループモードの「プレビュー」ボタンが非表示になります。',
      'settings.previewWindowMode': 'プレビューウィンドウモード',
      'settings.previewWindowModePopup': 'ポップアップウィンドウ（Game.exe）',
      'settings.previewWindowModeEmbedded': 'メインウィンドウ下部に埋め込む',
      'settings.showPreviewNotification': 'プレビュー開始時にゲーム内で「テキスト内容プレビューモード」を表示',
      'settings.previewNotificationPosition': '表示位置',
      'settings.previewNotificationPositionTopLeft': '左上',
      'settings.previewNotificationPositionTopCenter': '中央上',
      'settings.previewNotificationPositionTopRight': '右上',
      'settings.previewNotificationPositionBottomLeft': '左下',
      'settings.previewNotificationPositionBottomCenter': '中央下',
      'settings.previewNotificationPositionBottomRight': '右下',
      'settings.pickBackground': 'ローカル画像を参照',
      'settings.previewBackground': '背景をプレビュー',
      'settings.applyBackground': '適用（保存なし）',
      'settings.clearBackground': '背景をクリア',
      'settings.resetTheme': 'デフォルトに戻す',
      'settings.previewTitle': '背景プレビュー',
      'settings.previewEmpty': '背景画像が設定されていません',
      'settings.tabUI': 'インターフェース',
      'settings.tabTraditional': '従来型翻訳',
      'settings.tabLLM': 'LLM 翻訳',
      'settings.titleUI': 'インターフェース設定',
      'settings.titleTraditional': '従来型翻訳設定',
      'settings.titleLLM': 'LLM 翻訳設定',
      'settings.save': '設定を保存',
      'settings.close': '閉じる',
      'settings.baiduAppId': 'Baidu App ID',
      'settings.baiduAppIdPlaceholder': 'Baidu App ID を入力',
      'settings.baiduSecret': 'Baidu シークレットキー',
      'settings.baiduSecretPlaceholder': 'Baidu シークレットキーを入力',
      'settings.googleApiKey': 'Google API Key',
      'settings.googleApiKeyPlaceholder': 'Google API Key を入力',
      'settings.sourceLang': 'ソース言語',
      'settings.sourceLangPlaceholder': 'auto',
      'settings.targetLang': 'ターゲット言語',
      'settings.targetLangPlaceholder': 'zh-CN',
      'settings.traditionalHint': '従来型翻訳サービスを選択。Baidu は App ID とシークレット、Google は API Key が必要です。',
      'settings.llmHint': '高品質・キャラクター一貫性・スタイル翻訳に最適です。',
      'glossary.currentProject': '現在のプロジェクト',
      'glossary.emptyHint': '用語集が空です。下部から追加できます。',
      'glossary.termCountHint': 'この用語集には {count} 件の用語が含まれています。',
      'glossary.confirmDeleteTerm': '用語 "{source}" を削除しますか？',
      'glossary.confirmDeleteGlossary': '用語集 "{name}" を削除しますか？',
      'glossary.termAdded': '用語を追加しました：{source} → {target}',
      'glossary.termUpdated': '用語を更新しました：{source} → {target}',
      'glossary.termDeleted': '用語を削除しました：{source}',
      'glossary.created': '用語集を作成しました：{name}',
      'glossary.createdAt': '用語集を作成しました：{name}（{path}）',
      'glossary.createCanceled': '用語集の作成をキャンセルしました。',
      'glossary.createFailed': '用語集の作成に失敗しました',
      'glossary.saveAsApiMissing': '別名保存 API が未登録です',
      'glossary.exportApiMissing': 'エクスポート API が未登録です',
      'glossary.exportCanceled': 'エクスポートをキャンセルしました。',
      'glossary.exported': '用語集をエクスポートしました：{name}{path}',
      'glossary.imported': '用語集をインポートしました：{name}',
      'glossary.deleted': '用語集を削除しました：{name}',
      'glossary.saving': '用語集を保存中…',
      'glossary.creating': '用語集を作成中…',
      'glossary.exporting': '用語集をエクスポート中…',
      'glossary.importing': '用語集をインポート中…',
      'glossary.renaming': '用語集の名前を変更中：{from} → {to}',
      'glossary.loadProjectFirst': 'プロジェクトを先に開いてください',
      'glossary.importApiMissing': 'インポート API が未登録です',
      'glossary.saveFailed': '用語集の保存に失敗しました',
      'glossary.listInitFailed': '用語集リストの初期化に失敗しました',
      'glossary.listRefreshFailed': '用語集リストの更新に失敗しました',
      'glossary.exportFailed': 'エクスポートに失敗しました',
      'glossary.importFailed': 'インポートに失敗しました',
      'glossary.deleteFailed': '削除に失敗しました',
      'validation.tooManyLines': '{actual}/{max} 行',
      'validation.lineTooLong': '第{line}行{actual}/{max}文字',
      'validation.missingControlCodes': '制御コード不足 {codes}',
      'ai.defaultSystemPrompt': 'あなたはプロのRPG Makerゲーム漢化アシスタントです。原文を自然かつ正確に簡体字中国語に翻訳してください。',
      'ai.providerBaidu': '百度翻訳',
      'ai.providerGoogle': 'Google 翻訳',
      'ai.providerDeepseek': 'DeepSeek',
      'ai.providerKimi': 'Kimi（Moonshot AI）',
      'ai.providerGemini': 'Gemini',
      'ai.providerClaude': 'Claude / Anthropic',
      'ai.providerCustom': 'OpenAI 互換のカスタム API',
      'ai.apiKeyPlaceholder': 'API キーを入力',
      'ai.baseUrlPlaceholder': 'エンドポイント URL（例：https://api.deepseek.com/chat/completions）',
      'ai.modelPlaceholder': 'モデル名（例：deepseek-chat）',
      'ai.promptPlaceholder': 'システムプロンプト（任意）',
      'ai.kimiTutorialTitle': 'Kimi（Moonshot AI）設定ガイド',
      'ai.kimiStep1': '1. Kimi には独立した 2 つのエンドポイントがあり、API キーは互換性がありません。どちらか一方を選択：(a) 国際版：platform.kimi.ai にサインイン、base_url は https://api.moonshot.ai/v1。(b) 中国版：platform.moonshot.cn にサインイン、base_url は https://api.moonshot.cn/v1。キーとエンドポイントを取り違えると HTTP 401 が返ります。',
      'ai.kimiStep2': '2. 対応するコンソールの「API Keys」で「新規作成」を押し、sk- 始まりのキーをコピーして上の「API Key」欄に貼り付けます（右の目アイコンで表示切替）。',
      'ai.kimiStep3': '3. 「エンドポイント URL」もキーの出所に合わせて：https://api.moonshot.ai/v1（国際）または https://api.moonshot.cn/v1（中国）。/v1 は必須、/chat/completions は自動付与。',
      'ai.kimiStep4': '4. 普段の翻訳は moonshot-v1-8k（8K・最安）、長文は moonshot-v1-32k / moonshot-v1-128k、最高品質は kimi-k2.6 を推奨。',
      'ai.kimiStep5': '5. 廃止済み：kimi-latest（2026-01-28）と kimi-k2-*-preview 系列（2026-05-25）は使用しないでください。',
      'ai.kimiStep6': '6. 保存後「大規模モデル翻訳をテスト」で動作確認。401 が出た場合はキーとエンドポイントの組み合わせ違いが最も多いので、コンソールで発行元と残高を再確認してください。',
      'ai.toggleKeyShow': 'キーを表示',
      'ai.toggleKeyHide': 'キーを非表示',
      'ai.deepseekV4Flash': 'deepseek-v4-flash（公式推奨、非思考）',
      'ai.deepseekV4Pro': 'deepseek-v4-pro（公式推奨、思考）',
      'ai.deepseekChat': 'deepseek-chat（旧互換名、廃止予定）',
      'ai.deepseekReasoner': 'deepseek-reasoner（旧互換名、廃止予定）',
      'app.version': '· 1.2.0',
      'language.zhCN': '简体中文',
      'language.en': 'English',
      'language.ja': '日本語',
      'workspace.applyWritebackTitle': '現在の翻訳を新しい JSON に元の構造で書き戻す（元ファイルは上書きせず、localization_patch/data/ に出力）',
      'workspace.stopPreview': 'ゲーム内プレビューを停止',
      'workspace.stopPreviewTitle': 'ゲーム内プレビューを強制停止し、変更された元 JSON のバックアップを復元',
      'workspace.stoppingPreview': 'ゲーム内プレビューを停止してバックアップを復元中…',
      'workspace.returnToTitle': 'タイトルに戻る',
      'workspace.returnToTitleTitle': 'ゲームを閉じずにタイトル画面に戻る（F12）',
      'workspace.returningToTitle': 'タイトル画面に戻っています…',
      'workspace.returnedToTitle': 'タイトル画面に戻りました',
      'workspace.returnToTitleFailed': 'タイトル画面に戻れませんでした',
      'workspace.previewStopped': 'ゲーム内プレビューを停止しました',
      'workspace.previewStoppedRestored': '{files} 個のプレビューバックアップファイルを復元しました',
      'workspace.previewStopFailed': 'プレビューの停止に失敗しました',
      'workspace.previewProcessExited': 'ゲーム内プレビュープロセスが終了し、バックアップが復元されました',
      'project.previewBackupsRestored': '前回のクラッシュにより残存したプレビューバックアップを検出し、{files} 個のファイルを復元しました',
      'ai.prompt': 'システムプロンプト',
      'trace.project': 'プロジェクト',
      'trace.aiTranslate': 'AI翻訳',
      'trace.traditionalTranslate': '従来型翻訳',
      'trace.notice': '通知',
      'trace.status': '状態',
      'trace.assistPlatform': 'AI 翻訳補助',
      'trace.providerSwitched': '{provider} に切り替えました',
      'trace.uiSettings': 'UI 設定',
      'trace.uiSettingsSaved': 'UI 設定を保存しました。',
      'trace.backgroundImage': '背景画像',
      'trace.selectFailed': '選択に失敗しました',
      'trace.defaultThemeRestored': 'デフォルトの外観に戻しました',
      'trace.waiting': '操作を待っています…',
      'trace.initFailed': '初期化に失敗しました',
      'trace.unknownError': '不明なエラー',
      'trace.aiSettings': '大規模モデル翻訳設定',
      'trace.aiTest': '大規模モデル翻訳テスト',
      'trace.traditionalSettings': '従来型翻訳設定',
      'trace.traditionalTest': '従来型翻訳テスト',
      'app.copyright': '© 2026 RPG ローカライズ作業台。無断転載を禁じます。',
    
      'action.openProjectFolder': 'プロジェクトフォルダを開く',
      'action.loadProjectTexts': 'プロジェクトテキストを読み込む',
      'action.saveTranslatorSettings': '翻訳設定を保存',
      'action.testTranslatorSettings': '翻訳設定をテスト',
      'action.aiTranslate': 'AI 翻訳',
      'action.previewInGame': 'ゲーム内プレビュー',
      'action.repreviewInGame': 'プレビュー位置を更新',
      'action.returnToTitle': 'タイトルに戻る',
      'action.stopPreview': 'ゲーム内プレビューを停止',
      'action.saveProjectLastPosition': '翻訳位置を保存',
      'action.loadProjectProgressState': 'プロジェクト進捗を読み込む',
      'action.getUiSettings': 'UI 設定を取得',
      'action.saveUiSettings': 'UI 設定を保存',
      'trace.actionStart': 'アクション開始',
      'trace.actionSuccess': 'アクション完了',
      'trace.actionFailed': 'アクション失敗',
      'error.projectRequired': '{action}前にプロジェクトを開いて読み込んでください',
      'error.saveDraftApiMissing': '下書きエクスポート API が未注入です',
      'error.exportDraftFailed': '下書きエクスポートに失敗しました',
      'error.exportPatchApiMissing': 'パッチエクスポート API が未注入です',
      'error.exportPatchFailed': 'パッチエクスポートに失敗しました',
      'error.writebackApiMissing': '書き戻し API が未注入です',
      'error.writebackFailed': '書き戻しに失敗しました',
      'action.exportDraft': '下書きをエクスポート',
      'action.exportPatch': 'パッチをエクスポート',
      'action.writebackJson': 'JSON を書き戻す',
      'export.draftPending': '下書きをエクスポート中…',
      'export.draftSuccess': '下書きエクスポート完了',
      'export.draftError': '下書きエクスポートに失敗しました',
      'export.patchPending': 'パッチをエクスポート中…',
      'export.patchSuccess': 'パッチエクスポート完了',
      'export.patchError': 'パッチエクスポートに失敗しました',
      'trace.writebackClicked': 'ゲーム JSON 書き戻しをクリック',
      'action.openPatchDir': 'パッチディレクトリを開く',
      'error.noPatchDir': '開くパッチディレクトリがありません',
      'error.openDirApiMissing': 'ディレクトリを開く API が未注入です',
      'action.openingPatchDir': 'パッチディレクトリを開いています…',
      'action.patchDirOpened': 'パッチディレクトリを開きました',
      'action.openPatchDirFailed': 'パッチディレクトリを開けませんでした',
      'writeback.summary': '{count} 個の JSON ファイルを書き戻しました（エラー {errors} 件）',
    
      'project.recognized': '認識済み',
      'project.recognizedHint': 'プロジェクト構造を認識しました。インポートと翻訳を続行できます。',
      'project.dataRootsFound': 'テキストディレクトリ {count} 個を検出',
      'project.dataRootsEmpty': 'テキストディレクトリが見つかりません',
      'project.statusLoaded': 'プロジェクトを読み込みました',
      'project.statusDraft': '下書きを読み込みました',
      'project.statusLoading': 'プロジェクトを読み込み中…',
      'project.ready': 'プロジェクト準備完了：{path}',
      'trace.projectStatus': 'プロジェクト状態トレース',
      'trace.openProject': 'プロジェクトを開く',
      'trace.loadDraftBtn': '下書き読み込みボタン',
      'trace.prepareRead': '読み込み準備：{path}',
      'trace.callSystemDirPicker': 'システムディレクトリ選択器を呼び出し中',
      'trace.userCancel': 'ユーザーが選択をキャンセルしました',
      'trace.pickResult': '選択結果 rootDir={rootDir}, engine={engine}',
      'trace.mainProcessReturn': 'メインプロセスが返却 entries={entries}, warnings={warnings}',
      'trace.startPickDraftFile': '下書きファイルの選択を開始',
      'trace.draftOpened': '{path} を開きました',
      'common.processing': '処理中',
      'common.unknownError': '不明なエラー',
      'common.operationFailed': '操作に失敗しました',
      'draft.loadFailed': '下書きの読み込みに失敗しました',
      'draft.loaded': '下書きを読み込みました：{path}',
    },
  };

  function t(key, vars = {}) {
    const lang = localStorage.getItem('rpg-workbench-language') || 'zh-CN';
    const dict = i18n[lang] || i18n['zh-CN'];
    let text = dict[key] || i18n['zh-CN'][key] || key;
    Object.entries(vars).forEach(([k, v]) => { text = text.replaceAll(`{${k}}`, String(v)); });
    return text;
  }

  window.RpgI18n = i18n;
  window.RpgView = window.RpgView || {};
  window.RpgView.t = t;

  window.setVersionLabel = () => {
    const badge = document.getElementById('appVersionBadge');
    const copyright = document.getElementById('appCopyright');
    if (badge) badge.textContent = 'v 1.2.0';
    if (copyright) copyright.textContent = t('app.copyright');
  };

  window.showProjectStatus = window.showProjectStatus || (() => {});
  window.showAiStatus = window.showAiStatus || (() => {});
  window.showTraditionalStatus = window.showTraditionalStatus || (() => {});
  window.showToast = window.showToast || (() => {});
  window.setCallTraceStatus = window.setCallTraceStatus || (() => {});
  window.traceCall = window.traceCall || (() => {});
})();