name: Build and Release

on:
  push:
    tags:
      - 'v*' # 当你推行类似 v1.0.1 的标签时自动触发打包

jobs:
  release:
    runs-on: ${{ matrix.os }}

    strategy:
      matrix:
        os: [windows-latest, macos-latest] # 同时在微软和苹果的云端服务器上打包

    steps:
      - name: Check out git repository
        uses: actions/checkout@v4

      - name: Install Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 22

      - name: Install dependencies
        run: npm install

      - name: Build Electron App
        run: npm run build # 确保该命令能同时处理各自平台的编译

      - name: Upload Artifacts
        uses: actions/upload-artifact@v4
        with:
          name: build-${{ matrix.os }}
          path: dist/
